### PR TITLE
BUG: add SANITIZE_CTX for coordoperation is_instantiable and has_ballpark_transformation

### PR DESCRIPTION
**Pull request by snowman2**
This one was causing core dumping for me - had me digging through my code to find it and eventually I pinpointed the issue to these functions.

### CODE REVIEW

**Comment by kbevers** [comment]
Can you explain the circumstances of the core dump?

**Comment by rouault** [comment]
> Can you explain the circumstances of the core dump?

Pretty simple I think. If you passed ctx == NULL to this function, it failed to use the default global context, and thus a null pointer dereferece would occur.

@snowman2 So you use an implicit context in some places of your code ?

**Comment by kbevers** [comment]
> Pretty simple I think. If you passed ctx == NULL to this function, it failed to use the default global context, and thus a null pointer dereferece would occur.

Thanks. I am just trying to get enough info in here so I don't have to spend too much time writing release notes in two months time. This helps a lot!

**Comment by snowman2** [comment]
> So you use an implicit context in some places of your code ?

Not currently. Just testing it out for a potential solution to #1591 when I ran into this.

**Pull request merged**
