### PR TITLE
Remove autoconf build system (#2688)

### PR DESCRIPTION
**Pull request by rouault**
Maybe not for immediate merge, but at least to check our CI is now ready

### CODE REVIEW

**Comment by kbevers** [comment]
This is a big milestone! I agree that it needs a bit of time before merging still. One thing that immediately comes to my mind is an overhaul to `HOWTORELEASE`. There will be other things as well, I'm sure.

**Comment by mwtoews** [comment]
In a parallel world, I've been shaping a similar PR https://github.com/mwtoews/PROJ/tree/transition-ci-from-autotools-to-cmake (just the top commit). It just does the remaining CI transition. It's nearly ready. Should I create the PR for comparison?

**Comment by rouault** [comment]
> Should I create the PR for comparison?

from a quick glance it looks like your approach is better, so we should likely go with it

**Comment by mwtoews** [comment]
I'll push it when it's ready, perhaps tomorrow. Still typing up notes and chasing up macOS-specific failures.

**Comment by mwtoews** [comment]
See #3023 for the similar PR mentioned previously.

**Pull request closed without merging**
