### PR TITLE
Adding block-scoped comments in eqearth code

### PR DESCRIPTION
**Pull request by beuan**
This is addressing missed @busstoptaktik's comment on previous pull request #1101.
@busstoptaktik please review the changes.

### CODE REVIEW

**Review by busstoptaktik — COMMENTED** [review]
Looks better. I would have preferred if you had removed the superfluous braces and else-branches as well. But it really is a matter of taste.

You might as well consider reducing the scope of the for-local variables (tol and a few more) by moving their definition inside the for loop.

Finally, a comment about the 4 magic defines A1..A4 would be nice.

**Comment by beuan** [comment]
@busstoptaktik, changes applied. I hope I got them all.

**Comment by busstoptaktik** [comment]
Looks good to me - thanks for bothering with my nitpicks!

**Comment by busstoptaktik** [comment]
@kbevers  - I suppose you will want to merge this?

**Pull request merged**
