### PR TITLE
Zone Definition Fixes for igh_o projection

### PR DESCRIPTION
**Pull request by jkrasting**
- Central lon for zone 2 should be -d10, not d10
- Extra lobe was missing for zone 11
- New figure generated
- New test suite values generated

### CODE REVIEW

**Comment by rouault** [comment]
Looking at https://coveralls.io/builds/30876871/source?filename=src%2Fprojections%2Figh_o.cpp#L155 shows that a a few cases of the inverse method aren't covered by tests: lines 141, 145 and 155

**Comment by jkrasting** [comment]
> Looking at https://coveralls.io/builds/30876871/source?filename=src%2Fprojections%2Figh_o.cpp#L155 shows that a a few cases of the inverse method aren't covered by tests: lines 141, 145 and 155

a6bbde8 should address this - let's see.

**Comment by jkrasting** [comment]
> > Looking at https://coveralls.io/builds/30876871/source?filename=src%2Fprojections%2Figh_o.cpp#L155 shows that a a few cases of the inverse method aren't covered by tests: lines 141, 145 and 155
> 
> [a6bbde8](https://github.com/OSGeo/PROJ/commit/a6bbde8224f9dba625bc6ecbde36b3d8fb0e3f0c) should address this - let's see.

It does not look like my edits had and impact.  I don't really understand how the code coverage works.

**Comment by rouault** [comment]
>  I don't really understand how the code coverage works.

yes, that's weird. I suspect it isn't properly updated during the lifetime of a pull request if edits are done.

**Comment by jkrasting** [comment]
> > I don't really understand how the code coverage works.
> 
> yes, that's weird. I suspect it isn't properly updated during the lifetime of a pull request if edits are done.

I'll leave that to you, @rouault.  Very impressed by the infrastructure and testing associated with PROJ.  Kudos!

**Comment by kbevers** [comment]
I believe those lines are in fact tested, the reporting tools just does a poor job of showing it. 

The first and last line of the snippet below is marked as tested

```
case  11: ok = (lp.lam  >=  -d60-EPSLN && lp.lam <=   d90+EPSLN) ||
              ((lp.lam >=   d90-EPSLN && lp.lam <=  d100+EPSLN) && 
              (lp.phi  >=  -d90-EPSLN && lp.phi <=  -d40+EPSLN)); break;
```

This is two statements, the first one starting on the first line and ending at the last line. The seconda statement is the `break`. I believe the second line isn't marked green because not statements start or end in it.

**Pull request merged**
