### PR TITLE
Rename CMake infrastructure to remove 4

### PR DESCRIPTION
**Pull request by mwtoews**
A few CMake files were renamed and edited to remove the former major version number from them. Also a few old "[SOCI](https://github.com/SOCI/soci)" references were updated.

### CODE REVIEW

**Comment by kbevers** [comment]
Does this in any way interfere with #801 and #802?

**Comment by mwtoews** [comment]
Good point, I didn't consider these open issues. @cffk ?

As for `PROJ4_LIBRARIES` and `PROJ4_INCLUDE_DIRS` (which are not touched in this PR), they are only used in docs/source/development/cmake.rst. I only see `PROJ_LIBRARIES` used in various *.cmake files.

**Comment by kbevers** [comment]
I am sure most of this is fine. But I am worried that this `project(PROJ4 C)` -> `project(PROJ C)` could break something.

**Comment by cffk** [comment]
This PR breaks backward compatibility for cmake users.  The discussion lead by @kbevers a couple of months ago ended up deciding the although "proj" would be the official name of this project, proj4 would be retained in some contexts, e.g., proj4.org.  In particular, I liked the idea that

    find_project(PROJ4)
    target_link_libraries(${PROJ4_LIBRARIES})

 still "worked".  The change to CMakeLists.txt in this PR

    project(PROJ C)

breaks this.

**Comment by mwtoews** [comment]
The reference to the previous discussion where PROJ4 would be retained for CMake is #735

Question from the roll out plain in #789 : does the CMake `PROJECT-NAME` ever change to "PROJ"? And if so, at which release number?

**Comment by cffk** [comment]
In the plan described in #789, it was envisioned that the `PROJECT-NAME` stay as `PROJ4` indefinitely.  You could devise a separate plan to migrate from `PROJ4` to `PROJ` where for some period both names were supported.  I'm not sure this is necessary?

**Comment by mwtoews** [comment]
@cffk I've restored the previous `PROJECT-NAME` as `PROJ4` with a note for future readers. As far as I can see the only sensitive CMake [variable](https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html#id2) that needs attention is [`<PROJECT-NAME>_SOURCE_DIR`](https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_SOURCE_DIR.html) as `PROJ4_SOURCE_DIR`. I'm not sure if there are other CMake variables that provide provide information, and need to reference `PROJECT-NAME`. Is the CMake namespace restored with the previous commit? Any other concerns?

Also removed `${PROJ4_SOURCE_DIR}/cmake/modules`, which was another SOCI leftover (from `soci/cmake/modules/`) not used in this project.

**Pull request merged**
