### PR TITLE
Make a README from README.md when running 'make dist'

### PR DESCRIPTION
**Pull request by kbevers**
Fixing insufficient makefile update in 9e412249e5a7c6eaab1e73a11ca09e2bc7ca5df9

### CODE REVIEW

**Comment by mloskot** [comment]
Looks like the markdown conversion PR made you busy :(

`make[1]: *** No rule to make target `README.md', needed by `README'.  Stop.` is puzzling, the former does exist, doesn't it.

**Comment by kbevers** [comment]
Yes, I am quite aware of my limited knowledge of autotools right now. But I am learning a lot at least. I believe the problem now is files referenced in the Makefile is not correct when making out-of-source builds.

**Comment by mloskot** [comment]
I have no experienced with out of source builds using Autotools.

Might be easier to keep it in Markdown but rename `README.md` back to `README` until Autotools are dropped.

**Comment by kbevers** [comment]
Autotools is not likely to get dropped just yet though. I believe there's several "easy fixes" here that's close to perfect, for instance one option would be to add `README.md` to `EXTRA_DIST` and accept that two READMEs will be included in the source distribution. But I am not ready for that compromise just yet :-)

**Comment by kbevers** [comment]
The biggest problem for me is that all the various things I am trying works locally. Can't get to the bottom of the actual problem.

**Comment by kbevers** [comment]
The problem was in the travis setup. Running `make dist-all` from the source-distribution created from `make dist-all` is not going to work from here on. I would say that is reasonable.

**Comment by mloskot** [comment]
@kbevers Thank you for cleaning up the mess I've started :-)

**Pull request merged**
