### PR TITLE
Make NKG Transformation names unique

### PR DESCRIPTION
**Pull request by kbevers**
A consequence of new database constrains introduced in #4071.

Follow-up to https://github.com/OSGeo/PROJ/pull/4071#issuecomment-1984241613

### CODE REVIEW

**Comment by rouault** [comment]
LGTM and ready to be un-draft'ed

**Comment by kbevers** [comment]
I think the names are a bit on the long side but I suppose that doesn't matter much?

**Comment by rouault** [comment]
yes, that's perhaps a tidy bit verbose. e.g "'Intraplate deformation from ETRF2000@2000.0 to ETRF2000@2003.75 using realigned nkgrf03vel deformation model'" could be shorten as "ETRF2000@2000.0 to ETRF2000@2003.75 using nkgrf03vel"

**Comment by rouault** [comment]
@kbevers Are we going with the current names or do you plan to shorten them?

**Comment by kbevers** [comment]
> Are we going with the current names or do you plan to shorten them?

I'll shorten them. It's the easter holidays around here so work isn't my top priority these days but I'll get round to it soon enough :-)

**Comment by rouault** [comment]
No emergency. Enjoy your holidays

**Comment by rouault** [comment]
The backport to `9.4` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 36d75d30... Make NKG Transformation names unique
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging data/sql/proj_db_table_defs.sql
CONFLICT (content): Merge conflict in data/sql/proj_db_table_defs.sql

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-9.4 9.4
# Navigate to the new working tree
cd .worktrees/backport-9.4
# Create a new branch
git switch --create backport-4098-to-9.4
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 36d75d30ddc63eea663e9473663e3edbbfda65eb
# Push it to GitHub
git push --set-upstream origin backport-4098-to-9.4
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-9.4
```
Then, create a pull request where the `base` branch is `9.4` and the `compare`/`head` branch is `backport-4098-to-9.4`.

**Comment by rouault** [comment]
failed to make its way to 9.4

**Comment by kbevers** [comment]
> failed to make its way to 9.4

It did: https://github.com/OSGeo/PROJ/pull/4111

**Pull request merged**
