### PR TITLE
Fix testcct and add new cli tests to CMake setup

### PR DESCRIPTION
**Pull request by kbevers**
Should fix the failing tests

### CODE REVIEW

**Comment by kbevers** [comment]
> Should fix the failing tests

Well that didn't work 😕

**Comment by rouault** [comment]
@kbevers Ah sorry for this. I was overly confident on my ability to commit without CI checking me... Should be fixed hopefully by master commit 574eef1

**Comment by kbevers** [comment]
> @kbevers Ah sorry for this. I was overly confident on my ability to commit without CI checking me... 

Shit happens.

> Should be fixed hopefully by master commit [574eef1](https://github.com/OSGeo/proj.4/commit/574eef1bdb2b7a3f1bde9c485b94378288d0cf08)

Are you sure? There's also a typo in `CCTEXT`. That's what I fixed in c93d904

**Comment by rouault** [comment]
> There's also a typo in `CCTEXT`

Arg, ok committed that too..

**Comment by kbevers** [comment]
Right :-) I'll sync this branch with your changes then and get the tests up to date in CMake  too

**Pull request merged**
