### PR TITLE
Run gie tests with CMake and autotools builds

### LINKED ISSUE #702: Add gie tests in 'make check'
Currently the following tests are run after 'make check' in travis/install.sh. It would be good to have them as part of 'make check' itself, to ease local development

```
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/builtins.gie
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/more_builtins.gie
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/deformation.gie
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/axisswap.gie
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/ellipsoid.gie
PROJ_LIB=$GRIDDIR ./src/gie ./test/gie/GDA.gie
```

### PR DESCRIPTION
**Pull request by kbevers**
This adds the gie tests to the CMake and autotest testing facilities. GIGS tests have been converted from Python/json to gie and added as well. Note that some GIGS tests do not pass. The reason for this is described in #700. The failing tests are commented out for now.

Resolves #702.

### CODE REVIEW

**Comment by kbevers** [comment]
@cffk I get this error from `geodtest` on some of the CI targets. I suspect it is a problem on 32 bit only. Is that a plausable assumption?

```
assertEquals fails: 180 != -180 +/- 5e-006
GeodSolve61 fail: 1
```

**Comment by busstoptaktik** [comment]
Is this ready for merging (modulo a few conflicts) with the corrections supplied by @cffk in #719? or is this a different problem?

**Comment by kbevers** [comment]
> Is this ready for merging (modulo a few conflicts) with the corrections supplied by @cffk in #719? or is this a different problem?

Nope. I need to restructure the travis setup in some way. At the moment coverage is run with the autotools build and I want to run it with the cmake build instead. Additionally I think too many builds are made (2 x autotools, 2 x CMake IIRC).

Frankly, I figured I'd look into this once the GIGS tests can be run properly with gie (requires #700 be resolved), but I can take a look at this tomorrow and see if I can get it ready to be merged without the GIGS tests.

**Comment by busstoptaktik** [comment]
Don't worry, and don't hurry - I was just asking out of curiousity.

**Comment by kbevers** [comment]
Merging before appveyor tests are run since this shouldn't affect Windows.
 
GIGS gie tests haven't been added to the test suites yet, but will be as soon as #700 is finished.

**Pull request merged**
