### PR TITLE
Adding Natural Earth II and Compact Miller

### PR DESCRIPTION
**Pull request by beuan**
Adding the Natural Earth II projection #369 and the Compact Miller projection #370. Please verify. 
@QuLogic, @micahcochran, I hope this is the right way you were asking.

### CODE REVIEW

**Comment by hobu** [comment]
The tests do not pass yet. They will have to pass for this to be merged.

Thanks for the contribution!

**Comment by micahcochran** [comment]
@beuan That is exactly what I was suggesting.  Thank you!

Is there a unit test for Natural Earth II?

**Comment by beuan** [comment]
@micahcochran Great! I do not have a test for the Natural Earth II. Also, I am having a problem with the Compact Miller test. I do not see the difference in tv-out.dist file.

**Comment by micahcochran** [comment]
> I do not see the difference in tv-out.dist file.

I didn't see it either.  It is probably a space when it should be a tab.  I suggest using [Meld ](http://meldmerge.org/) to highlight the differences.

**Comment by micahcochran** [comment]
I used Flex Projector to project these points (via shapefile) into Natural Earth 2.  I took it out to 8 decimal points.  These are comma delimited,  so I know it will need a little modification.

I'm not sure if I'm being helpful or not.  :smiling_imp: 

**Input table (lon, lat):**

```
0,0.0
0,22.5
0,45.0
0,67.5
0,90.0
45,0.0
45,22.5
45,45.0
45,67.5
45,90.0
90,0.0
90,22.5
90,45.0
90,67.5
90,90.0
135,0.0
135,22.5
135,45.0
135,67.5
135,90.0
180,0.0
180,22.5
180,45.0
180,67.5
180,90.0
```

**Output Table (X,Y)**

```
0.00000000,0.00000000
0.00000000,2531453.57080958
0.00000000,5051471.50086845
0.00000000,7395411.22478983
0.00000000,9073776.52662810
4239151.18200719,0.00000000
4138348.61904244,2531453.57080958
3830621.33880773,5051471.50086845
3158326.32836996,7395411.22478983
957973.37034235,9073776.52662810
8478302.36401439,0.00000000
8276697.23808488,2531453.57080958
7661242.67761547,5051471.50086845
6316652.65673992,7395411.22478983
1915946.74068470,9073776.52662810
12717453.54602160,0.00000000
12415045.85712730,2531453.57080958
11491864.01642320,5051471.50086845
9474978.98510988,7395411.22478983
2873920.11102705,9073776.52662810
16956604.72802880,0.00000000
16553394.47616980,2531453.57080958
15322485.35523090,5051471.50086845
12633305.31347990,7395411.22478983
3831893.48136940,9073776.52662810
```

**Comment by micahcochran** [comment]
Perhaps something like [icdiff](https://www.jefftk.com/icdiff) would work better for Travis testing.  It requires Python.

**Comment by beuan** [comment]
@micahcochran thanks! It was very helpful. I also think, I finally figured the test for the Compact Miller projection.

**Comment by beuan** [comment]
@hobu I was able to fix the problem and tests passed. Thanks!

**Comment by micahcochran** [comment]
Good work @beuan

**Comment by beuan** [comment]
@micahcochran Thanks

**Pull request merged**
