### PR TITLE
Database: update to EPSG v11.025

### PR DESCRIPTION
**Pull request by rouault**
@jratike80 This EPSG release brings finally the Finland geoid models (and bonus points as GTG files). Is there going to be a pull request against https://github.com/OSGeo/PROJ-data/ to add the grids?

### CODE REVIEW

**Comment by jjimenezshaw** [comment]
> @jratike80 This EPSG release brings finally the Finland geoid models (and bonus points as GTG files). Is there going to be a pull request against https://github.com/OSGeo/PROJ-data/ to add the grids?

I started it some time ago. I can search that branch somewhere in my computer.

**Comment by jratike80** [comment]
@jjimenezshaw , do you have the geoid models in tiff format (fi_nls_fin2023n2000.tif, fi_nls_fin2000.tif)? I have some self-made versions which I converted from ASCII but they are not checked.
I do not know is Pasi Häkli has GitHub account but I can try to reach him per email.

**Comment by jjimenezshaw** [comment]
@jratike80 I did this some time ago
https://github.com/jjimenezshaw/PROJ-data/commit/72eb6fa7b6bdb98422fafc73bab031e4b373a4c3
I can review it tomorrow

**Comment by kbevers** [comment]
> I do not know is Pasi Häkli has GitHub account but I can try to reach him per email.

He does: @phakli

**Comment by jjimenezshaw** [comment]
I am updating the scripts of my branch to include also `fi_nls_fin2023n2000.tif`, and declare they use EUREF-FIN (EPSG:10689).
Once this PR (#4350) is merged I will continue with it; I need EPSG:10689 in proj.db

To convert the ASCII files (*.lst) I am using the same workflow as usualy, with a bash script included in the branch. You can already have a look.

**Comment by jratike80** [comment]
@jjimenezshaw , check the newest model https://www.maanmittauslaitos.fi/sites/maanmittauslaitos.fi/files/attachments/2023/12/FIN2023N2000_lst.zip, documented in https://www.maanmittauslaitos.fi/en/maps-and-spatial-data/coordinates-and-positioning/koordinaattimuunnokset/fin2023n2000-geoidimalli

**Comment by jjimenezshaw** [comment]
Interestingly, the projected system [EPSG:3067](https://epsg.org/crs_3067/ETRS89-TM35FIN-E-N-.html), previously named `ETRS89 / TM35FIN(E,N)` is now `EUREF-FIN / TM35FIN(E,N)`, changing not only the name, but the base CRS. (EUREF-FIN is a realization of ETRS89)

And this is one of those CRSs with two areas of use.

**Comment by jratike80** [comment]
Right, when the EUREF-FIN datum was added https://epsg.org/datum_1391/EUREF-FIN.html, there were two alternatives. Either to register a new set of CRS codes for EUREF-FIN, or to edit the definitions of the existing codes. There are quite many codes affected https://epsg.org/closed-change-request/browse/id/[2024.062](https://epsg.org/closed-change-request/browse/id/2024.062).

Some confusion is inevident but we considered that most users who use the established EPSG:3067 etc. will not suffer from the base CRS change.

**Comment by phakli** [comment]
Glad to see that the inclusion of the Finnish geoid models to PROJ is already in progress, thanks @jjimenezshaw. That would've been our next task. I had already started testing with some self-converted gtg files but they were not produced according to PROJ contributing guidelines yet. And, as we are novices with contributing to PROJ, we were only about to start checking the guidelines. So, to make things right and faster, we appreciate and support your efforts. We can help as much as we can, at least testing the grids and checking the information if needed.

By the way, IOGP has also included our TINshift-based transformations to EPSG registry, see EPSG:10703-10705. Is there something we should do with these regarding the PROJ?

**Comment by jjimenezshaw** [comment]
@phakli There is already a PR with the grid files at https://github.com/OSGeo/PROJ-data/pull/131
please, check them and the metadata.
If you compile "master" branch from PROJ (that includes the latest version of EPSG) and use those grid files, it should work directly.

**Comment by jratike80** [comment]
Hi,

I checked the TIFF files with gdalinfo.  Pixel sizes, extents, and metadata tags look good to me.  I believe that MMT here means MML (MaanMittausLaitos). MMT refers usually to Doctor of Agriculture and Forestry. But maybe MML would not add any value, while the full name National Land Survey of Finland might do that.

`TIFFTAG_COPYRIGHT=Derived from work by NLS (MMT) Finland. CC-BY-4.0 https://creativecommons.org/licenses/by/4.0/`

**Comment by jjimenezshaw** [comment]
> Hi,
> 
> I checked the TIFF files with gdalinfo. Pixel sizes, extents, and metadata tags look good to me. I believe that MMT here means MML (MaanMittausLaitos). MMT refers usually to Doctor of Agriculture and Forestry. But maybe MML would not add any value, while the full name National Land Survey of Finland might do that.
> 
> `TIFFTAG_COPYRIGHT=Derived from work by NLS (MMT) Finland. CC-BY-4.0 https://creativecommons.org/licenses/by/4.0/`

@jratike80  Answered in https://github.com/OSGeo/PROJ-data/pull/131

**Comment by rouault** [comment]
> By the way, IOGP has also included our TINshift-based transformations to EPSG registry, see EPSG:10703-10705. Is there something we should do with these regarding the PROJ?

support for them queued in https://github.com/OSGeo/PROJ/pull/4353

**Pull request merged**
