### PR TITLE
ob_tran: restore traditional handling of +to_meter with pj_transform() and proj utility (fixes #1782)

### LINKED ISSUE #1782: 'to_meter' on 'proj=ob_tran o_proj=latlon' broke in 6.1.1
In Cartopy, there is a `RotatedGeodetic` CRS which uses 'ob_tran' to define a rotated coordinate system, using degrees with 'o_proj=latlon'. It specifies `to_meter=math.radians(1)` to produce results in degrees as well. Cartopy has not been updated to use any new API, so a transform from `PlateCarree` to `RotatedGeodetic` is something like:

```
pj_transform("+ellps=WGS84 +a=57.29577951308232 +proj=eqc +lon_0=0.0 +no_defs"
             "+ellps=WGS84 +proj=ob_tran +o_proj=latlon +o_lon_p=0.0 +o_lat_p=90.0 +lon_0=360.0 +to_meter=0.0174532925199433 +no_defs",
             nx, ny, &x, &y, NULL);
```
(I am skipping all the init stuff here, of course.)

The pole location and rotation angle _should_ result in no change to the result. Starting with 6.1.1, the `to_meter` has no effect and results are `to_meter` times smaller than they should be (or the inverse, if transforming in reverse.) For example, with 6.1.0, some test points are:
```
(-179, -89) -> (-179.00000000000003, -89.00000000000007)
(-179, 0) -> (-179.00000000000003, 3.507820309861257e-15)
(-179, 89) -> (-179.00000000000003, 89.00000000000007)
(0, -89) -> (0.0, -89.00000000000007)
(0, 0) -> (0.0, -3.508354649267437e-15)
(0, 89) -> (0.0, 89.00000000000007)
(179, -89) -> (178.99999999999997, -89.00000000000007)
(179, 0) -> (178.99999999999997, 3.507820309861257e-15)
(179, 89) -> (178.99999999999997, 89.00000000000007)
```
but with 6.1.1, the results are:
```
(-179, -89) -> (-3.124139361069851, -1.553343034274955)
(-179, 0) -> (-3.124139361069851, 6.122301397540666e-17)
(-179, 89) -> (-3.124139361069851, 1.553343034274955)
(0, -89) -> (0.0, -1.553343034274955)
(0, 0) -> (0.0, -6.123233995736766e-17)
(0, 89) -> (0.0, 1.553343034274955)
(179, -89) -> (3.12413936106985, -1.553343034274955)
(179, 0) -> (3.12413936106985, 6.122301397540666e-17)
(179, 89) -> (3.12413936106985, 1.553343034274955)
```

I can also reproduce this directly with `proj`, 6.1.0:
```
for lon in -179 0 179; do
 for lat in -89 0 89; do
  echo $lon $lat
 done
done | proj -E +ellps=WGS84 +proj=ob_tran +o_proj=latlon +o_lon_p=0.0 +o_lat_p=90.0 +lon_0=360.0 +to_meter=0.0174532925199433 +no_defs

-179 -89        -179.00 -89.00
-179 0  -179.00 0.00
-179 89 -179.00 89.00
0 -89   0.00    -89.00
0 0     0.00    -0.00
0 89    0.00    89.00
179 -89 179.00  -89.00
179 0   179.00  0.00
179 89  179.00  89.00
```
vs 6.1.1:
```
for lon in -179 0 179; do
 for lat in -89 0 89; do
  echo $lon $lat
 done
done | proj -E +ellps=WGS84 +proj=ob_tran +o_proj=latlon +o_lon_p=0.0 +o_lat_p=90.0 +lon_0=360.0 +to_meter=0.0174532925199433 +no_defs

-179 -89        -3.12   -1.55
-179 0  -3.12   0.00
-179 89 -3.12   1.55
0 -89   0.00    -1.55
0 0     0.00    -0.00
0 89    0.00    1.55
179 -89 3.12    -1.55
179 0   3.12    0.00
179 89  3.12    1.55
```

Bisect says this started with 11a53b7c0255087c2b324b36147deb837902dfb9.

### PR DESCRIPTION
**Pull request by rouault**
Fixes side-effect of https://github.com/OSGeo/PROJ/issues/1525 that went in 6.1.1

The correction is horribly hacky. Sorry...

### CODE REVIEW

**Review by kbevers — CHANGES_REQUESTED** [review]
> The correction is horribly hacky. Sorry...

Too hacky in my opinion. I don't think there's a way around a hacky solution but at least it should be localized to `ob_tran`. I think that should be possible by doing a checking what type of projection is used in `o_forward()` and then scaling the values so they come out as degrees.

**Comment by rouault** [comment]
>  I think that should be possible by doing a checking what type of projection is used in `o_forward()` and then scaling the values so they come out as degrees.

That's pretty much what we already do in ob_tran.cpp with
```
    /* Support some rather speculative test cases, where the rotated projection */
    /* is actually latlong. We do not want scaling in that case... */
    if (Q->link->right==PJ_IO_UNITS_RADIANS)
        P->right = PJ_IO_UNITS_WHATEVER;
```

The reallity is that ob_tran has always been hacky. With the new interface of proj_create_crs_to_crs(), it is somewhat less hacky since we don't require any more (and no longer honour) the to_meter=0.0174532925199433 . Hence adding back the hack only when invoked from the ancient API.

I'm happy to let you find a better solution if you can think of one that doesn't make the fix of #1525 regress...

**Comment by kbevers** [comment]
> That's pretty much what we already do in ob_tran.cpp with

Except that it is done in the setup and not on the individual coordinate. I would put in a check similar to 

```
    if( Proj->right == PJ_IO_UNITS_WHATEVER && Proj->descr &&
        strncmp(Proj->descr, "General Oblique Transformation",
                strlen("General Oblique Transformation")) == 0 )
    {
        Proj->right = PJ_IO_UNITS_PROJECTED;
    }
```

in `o_forward()`. 

> I'm happy to let you find a better solution if you can think of one that doesn't make the fix of #1525 regress...

I'd like to give it a go. I'm a bit overloaded at the moment but I think I can manage to squeeze in some time in the weekend.

**Comment by rouault** [comment]
One thing I considered to make it slightly less awkward was to add a "int is_ob_trans" member in struct PJconsts, to avoid the string comparison.

> Except that it is done in the setup and not on the individual coordinate

I don't think this will have measurable runtime impact as it is done outside of the loop that transforms several coordinates at once and the Proj->right == PJ_IO_UNITS_WHATEVER  comparison is going to be false for pretty much all projection methods, so the string comparison should be done only in a few cases

> I would put in a check similar to in o_forward()

We do want a different behaviour depending if we use it through proj_create() or pj_transform(), so I'm not sure the solution can come from a change in ob_tran.cpp itself. Happy to be be proven wrong ! Or perhaps through all the magic that occurs in fwd.cpp / inv.cpp with the pre and post processing stages.

**Comment by kbevers** [comment]
> We do want a different behaviour depending if we use it through proj_create() or pj_transform(), so I'm not sure the solution can come from a change in ob_tran.cpp itself. Happy to be be proven wrong ! Or perhaps through all the magic that occurs in fwd.cpp / inv.cpp with the pre and post processing stages.

Good point about the differing behaviour in pj_transform() and proj_create(). It could be that the pre- and post-processing stages are the correct place to fix this.

**Review by kbevers — APPROVED** [review]
I didn't find the time to look at this. The hacky fix it is!

**Pull request merged**
