### PR TITLE
Azimuthal Equidistant projection is not accurate

### PR DESCRIPTION
**Pull request by cffk**
#246 Azimuthal Equidistant projection is not accurate

Here is the patch to resolve this issue.  This is bbauerma;s with a
few changes by me.

  --Charles

### CODE REVIEW

**Comment by QuLogic** [comment]
Are you sure you want to use a single `geod_geodesic` instance? Will that be okay if there are multiple instances of the `proj` object?

The modified patch I posted on trac does not share the `geod_geodesic` if you think that is better (I don't know for sure.)

**Comment by cffk** [comment]
You're quite right.  The trac site is down right now so I can't take a look at your fix.  Presumably
it's to add the geod_geodesic to PROJ_PARMS__?  I'll make the fix as soon as trac is up
again.

**Comment by QuLogic** [comment]
Please rebase or re-create your fork, as the flattening of the directory structure caused all commits to be re-written.

**Comment by cffk** [comment]
Done.  But since I didn't reference this issue number, the pull request is on #281 .

**Comment by QuLogic** [comment]
FYI, you did not need to open a new PR. GitHub will sync the PR with your branch, so you'd just need to reset the `aeqd` branch to match the new `aeqd-2`, and force push to replace it on the server.

**Comment by cffk** [comment]
OK, thanks for the information.  Still learning my way around github...

**Comment by rouault** [comment]
It seems that this PR is a duplicate of #281 ? Closing under that assumption.

**Pull request closed without merging**
