### PR TITLE
Fix wrong results with SQLite 3.38.0 (fixes #3077)

### LINKED ISSUE #3077: testprojinfo & proj_test_cpp_api test failure
#### Example of problem
The Debian package build for 9.0.0 failed due to test failures:
```
45: diff testprojinfo_out with testprojinfo_out.dist
45: --- testprojinfo_out        2022-03-01 19:36:15.950534825 +0000
45: +++ /build/proj-9.0.0/test/cli/testprojinfo_out.dist        2022-02-23 18:51:04.000000000 +0000
45: @@ -1270,14 +1270,25 @@
45:    +step +proj=axisswap +order=2,1
45:  
45:  Testing -s "AGD66" -t "WGS 84 (G1762)" --spatial-test intersects --summary. Should include a transformation through GDA2020
45: -Candidate operations found: 8
45: -unknown id, AGD66 to WGS 84 (1) + WGS 84 to WGS 84 (G1762), 8 m, Australia - Australian Capital Territory; New South Wales; Northern Territory; Queensland; South Australia; Tasmania; Western Australia; Victoria.
45: +Candidate operations found: 19
45: +unknown id, AGD66 to WGS 84 (18) + WGS 84 to WGS 84 (G1762), 5 m, Australia - offshore including EEZ.
45: +unknown id, AGD66 to WGS 84 (16) + WGS 84 to WGS 84 (G1762), 7 m, Australia - Australian Capital Territory; New South Wales; Northern Territory; Queensland; South Australia; Tasmania; Western Australia; Victoria.
45: +unknown id, AGD66 to WGS 84 (20) + WGS 84 to WGS 84 (G1762), 11 m, Australia - Australian Capital Territory; New South Wales; Northern Territory; Queensland; South Australia; Tasmania; Western Australia; Victoria.
45: +unknown id, AGD66 to WGS 84 (15) + WGS 84 to WGS 84 (G1762), 5 m, Australia - Northern Territory.
45: +unknown id, AGD66 to WGS 84 (13) + WGS 84 to WGS 84 (G1762), 5 m, Australia - New South Wales and Victoria.
45: +unknown id, AGD66 to WGS 84 (21) + WGS 84 to WGS 84 (G1762), 7 m, Papua New Guinea - mainland onshore.
45: +unknown id, AGD66 to WGS 84 (14) + WGS 84 to WGS 84 (G1762), 5 m, Australia - Tasmania including islands - onshore.
45: +unknown id, AGD66 to WGS 84 (19) + WGS 84 to WGS 84 (G1762), 4 m, Papua New Guinea - Papuan fold and thrust belt.
45: +unknown id, AGD66 to WGS 84 (22) + WGS 84 to WGS 84 (G1762), 6 m, Papua New Guinea - Papuan fold and thrust belt.
45: +unknown id, AGD66 to WGS 84 (23) + WGS 84 to WGS 84 (G1762), 6 m, Papua New Guinea - North Fly area (between 5°04'S and 6°36'S and west of 141°32'E).
45: +unknown id, AGD66 to WGS 84 (12) + WGS 84 to WGS 84 (G1762), 5 m, Australia - Australian Capital Territory.
45: +unknown id, AGD66 to GDA94 (11) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 0.75 m, Australia - Australian Capital Territory; New South Wales; Northern Territory; Queensland; South Australia; Tasmania; Western Australia; Victoria.
45: +unknown id, AGD66 to GDA94 (12) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 3.25 m, Australia - Australian Capital Territory; New South Wales; Northern Territory; Queensland; South Australia; Tasmania; Western Australia; Victoria.
45:  unknown id, AGD66 to WGS 84 (17) + WGS 84 to WGS 84 (G1762), 4.9 m, Australia - Australian Capital Territory; New South Wales; Northern Territory; Queensland; South Australia; Tasmania; Western Australia; Victoria.
45: -unknown id, AGD66 to GDA94 (3) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 1.25 m, Australia - Tasmania including islands - onshore.
45: -unknown id, AGD66 to GDA94 (2) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 1.25 m, Australia - Australian Capital Territory.
45: -unknown id, AGD66 to GDA94 (7) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 0.35 m, Australia - Northern Territory.
45: -unknown id, AGD66 to GDA94 (10) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 0.35 m, Australia - Australian Capital Territory, New South Wales, Victoria.
45: -unknown id, AGD66 to GDA94 (6) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 0.35 m, Australia - Tasmania including islands - onshore.
45: +unknown id, AGD66 to GDA94 (9) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 1.25 m, Australia - Northern Territory.
45: +unknown id, AGD66 to GDA94 (4) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 1.25 m, Australia - New South Wales and Victoria.
45: +unknown id, AGD66 to GDA94 (8) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 1.25 m, Australia - Tasmania including islands - onshore.
45: +unknown id, AGD66 to GDA94 (19) + GDA94 to GDA2020 (2) + Conversion from GDA2020 (geog2D) to GDA2020 (geocentric) + GDA2020 to WGS 84 (G1762) (1) + Conversion from WGS 84 (G1762) (geocentric) to WGS 84 (G1762) (geog2D), 0.75 m, Australia - Australian Capital Territory.
45:  unknown id, Ballpark geographic offset from AGD66 to WGS 84 (G1762), unknown accuracy, World, has ballpark transformation
45:  
45:  Testing -s EPSG:31467 -t ETRS89 --spatial-test intersects --grid-check none --bbox 8,48,9,49 --summary. Should include both DHDN to ETRS89 (8) and DHDN to ETRS89 (BWTA2017)
45: @@ -1536,6 +1547,8 @@
45:    +step +proj=axisswap +order=2,1
45:    +step +proj=unitconvert +xy_in=deg +xy_out=rad
45:    +step +proj=tmerc +lat_0=0 +lon_0=27 +k=1 +x_0=3500000 +y_0=0 +ellps=intl
45: +  +step +proj=tinshift +file=fi_nls_n43_n60.json
45: +  +step +proj=tinshift +file=fi_nls_n60_n2000.json
45:    +step +proj=tinshift +file=fi_nls_ykj_etrs35fin.json
45:    +step +inv +proj=utm +zone=35 +ellps=GRS80
45:    +step +proj=unitconvert +xy_in=rad +xy_out=deg
45: @@ -1544,6 +1557,8 @@
45:  Testing -s "KKJ / Finland Uniform Coordinate System + N43 height" -t "ETRS89 / TM35FIN(E,N) + N2000 height" --grid-check none -o PROJ -q
45:  +proj=pipeline
45:    +step +proj=axisswap +order=2,1
45: +  +step +proj=tinshift +file=fi_nls_n43_n60.json
45: +  +step +proj=tinshift +file=fi_nls_n60_n2000.json
45:    +step +proj=tinshift +file=fi_nls_ykj_etrs35fin.json
45:  
45:  Testing -s "ETRS89 / TM35FIN(E,N) + N2000 height" -t "KKJ / Finland Uniform Coordinate System + N43 height" --grid-check none -o PROJ -q
45: 
45: PROBLEMS HAVE OCCURRED
45: test file testprojinfo_out saved
45: 
```
```
51: ./test/unit/test_operationfactory.cpp:6153: Failure
51: Expected equality of these values:
51:   list.size()
51:     Which is: 1
51:   2U
51:     Which is: 2
```
[Full buildlog](https://github.com/OSGeo/PROJ/files/8164352/proj_9.0.0-1.exp1_amd64.txt)

Since 9.0.0-rc2 sqlite3 was updated from 3.37.2-2 to 3.38.0-1, and libxml2 was updated from 2.9.12+dfsg-6 to 2.9.13+dfsg-1.

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by rhuijben** [comment]
I think you should limit this disabling with a specific runtime version check against the SQLite version, as this tweak is generally untested by the SQLite developers... And not guaranteed stable over all versions.

**Comment by rhuijben** [comment]
Usually SQLite releases a patch release soon after a problem like this is found. Which is the proper long time fix...

The fix is already committed in SQLite development.. so, I would expect 3.38.0.1 or 3.38.1 in a few days.

**Comment by rhuijben** [comment]
Maybe we should just fail on this specific patch release on build/configure. That would be an easy way for packagers to know they should skip that version. (We used that route for Subversion, while introducing the SQLite working copy)

**Comment by rhuijben** [comment]
*Update*: 3.38.1 is being prepared

**Comment by rouault** [comment]
> I think you should limit this disabling with a specific runtime version check against the SQLite version,

done

**Pull request merged**
