### PR TITLE
proj.db opening: allow opening with a URI (typically for memvfs) (fixes #3887)

### LINKED ISSUE #3887: cannot open proj.db with memvfs
Hi I try to use the proj to load the proj.db in memory format. To do this, I use char proj_db[] to store the proj.db in binary format, and load it by memvfs. But when I run the code, I get the error of open file. I wonder if there something wrong in my codes?

Here is my code:
```c
#include <math.h>
#include <proj.h>
#include <filemanager.hpp>
#include <stdio.h>
#include <iostream>
#include "sqlite3.h"

extern "C" unsigned char proj_db[];
extern "C" unsigned int proj_db_len;
extern "C" int sqlite3_memvfs_init(sqlite3 *, char **, const sqlite3_api_routines *);

int main(void) {

    sqlite3_initialize();
    sqlite3_memvfs_init(nullptr, nullptr, nullptr);
    auto vfs = sqlite3_vfs_find("memvfs");
    if (!vfs) {
        std::cerr << "Could not find sqlite memvfs extension\n";
        return -1;
    }
    sqlite3_vfs_register(vfs, 0);

    /* Create the context. */
    /* You may set C=PJ_DEFAULT_CTX if you are sure you will     */
    /* use PJ objects from only one thread                       */
    PJ_CONTEXT *C = proj_context_create();

    char * path = sqlite3_mprintf("file:/proj.db?ptr=0x%p&sz=%lld&freeonclose=1", (void *)proj_db, (long long)proj_db_len);
    proj_context_set_sqlite3_vfs_name(C, "memvfs");
    bool ok = proj_context_set_database_path(C, path, nullptr, nullptr);

    if (!ok)
    {
        std::cerr << "canno open set the database path\n";
        return -1;
    }

    return 0;
}
```

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by gaoyuanning** [comment]
Hi rouault, the example code (https://proj.org/en/9.3/development/quickstart.html) will coredump when I try to run it after add `SQLITE_OPEN_URI` flag. I found the coredump triggered in `proj_context_destroy(C)` when we try to destroy the context. 

Thanks for fixing this issue. Looking forward to your reply.

```C++
#include <math.h>
#include <proj.h>
#include <filemanager.hpp>
#include <stdio.h>
#include <iostream>
#include "sqlite3.h"

extern "C" unsigned char proj_db[];
extern "C" unsigned int proj_db_len;
extern "C" int sqlite3_memvfs_init(sqlite3 *, char **, const sqlite3_api_routines *);

int main(void) {
    sqlite3_initialize();
    sqlite3_memvfs_init(nullptr, nullptr, nullptr);
    auto vfs = sqlite3_vfs_find("memvfs");
    if (!vfs) {
	std::cerr << "Could not find sqlite memvfs extension\n";
        return -1;
    }
    sqlite3_vfs_register(vfs, 0);

    /* Create the context. */
    /* You may set C=PJ_DEFAULT_CTX if you are sure you will     */
    /* use PJ objects from only one thread                       */
    PJ_CONTEXT *C = proj_context_create();

    char * path = sqlite3_mprintf("file:/proj.db?ptr=0x%p&sz=%lld&freeonclose=1", (void *)proj_db, (long long)proj_db_len);

    proj_context_set_sqlite3_vfs_name(C, "memvfs");

    bool ok = proj_context_set_database_path(C, path, nullptr, nullptr);

    /* Create a projection. */
    PJ *P = proj_create(C, "+proj=utm +zone=32 +datum=WGS84 +type=crs");

    if (0 == P) {
        fprintf(stderr, "Failed to create transformation object.\n");
        return 1;
    }

    /* Get the geodetic CRS for that projection. */
    PJ *G = proj_crs_get_geodetic_crs(C, P);

    /* Create the transform from geodetic to projected coordinates.*/
    PJ_AREA *A = NULL;
    const char *const *options = NULL;
    PJ *G2P = proj_create_crs_to_crs_from_pj(C, G, P, A, options);

    /* Longitude and latitude of Copenhagen, in degrees. */
    double lon = 12.0, lat = 55.0;

    /* Prepare the input */
    PJ_COORD c_in;
    c_in.lpzt.z = 0.0;
    c_in.lpzt.t = HUGE_VAL; // important only for time-dependent projections
    c_in.lp.lam = lon;
    c_in.lp.phi = lat;
    printf("Input longitude: %g, latitude: %g (degrees)\n", c_in.lp.lam,
           c_in.lp.phi);

    /* Compute easting and northing */
    PJ_COORD c_out = proj_trans(G2P, PJ_FWD, c_in);
    printf("Output easting: %g, northing: %g (meters)\n", c_out.enu.e,
           c_out.enu.n);

    /* Apply the inverse transform */
    PJ_COORD c_inv = proj_trans(G2P, PJ_INV, c_out);
    printf("Inverse applied. Longitude: %g, latitude: %g (degrees)\n",
           c_inv.lp.lam, c_inv.lp.phi);

    /* Clean up */
    proj_destroy(P);
    proj_destroy(G);
    proj_destroy(G2P);
    // The coredump happened when destory the context
    proj_context_destroy(C); /* may be omitted in the single threaded case */
    return 0;
}
```

```
Input longitude: 12, latitude: 55 (degrees)
Output easting: 691876, northing: 6.09891e+06 (meters)
Inverse applied. Longitude: 12, latitude: 55 (degrees)
*** Error in `./proj1': free(): invalid pointer: 0x00000000005c17e8 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7f7cfc8c8bfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7f7cfc8cefc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7f7cfc8cf80e]
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0(sqlite3_free+0x4b)[0x7f7cfd54e35b]
./proj1[0x5bde2f]
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0(+0x71295)[0x7f7cfd5a4295]
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0(+0x843ce)[0x7f7cfd5b73ce]
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0(+0x845d3)[0x7f7cfd5b75d3]
/usr/lib/x86_64-linux-gnu/libsqlite3.so.0(+0x84bb2)[0x7f7cfd5b7bb2]
./proj1[0x379afb]
./proj1[0x378449]
/lib/x86_64-linux-gnu/libc.so.6(+0x35940)[0x7f7cfc88d940]
/lib/x86_64-linux-gnu/libc.so.6(+0x3599a)[0x7f7cfc88d99a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf8)[0x7f7cfc8782e8]
./proj1[0x2c56aa]
======= Memory map: ========
00200000-002c5000 r--p 00000000 09:0a 822068775                          /data01/gaoyuanning/Code_Test/proj/proj1
002c5000-005c0000 r-xp 000c4000 09:0a 822068775                          /data01/gaoyuanning/Code_Test/proj/proj1
005c0000-005c1000 r--p 003be000 09:0a 822068775                          /data01/gaoyuanning/Code_Test/proj/proj1
005c1000-00dad000 rw-p 003be000 09:0a 822068775                          /data01/gaoyuanning/Code_Test/proj/proj1
00dad000-00db0000 rw-p 00000000 00:00 0
01a61000-01d27000 rw-p 00000000 00:00 0                                  [heap]
7f7cf8000000-7f7cf8021000 rw-p 00000000 00:00 0
7f7cf8021000-7f7cfc000000 ---p 00000000 00:00 0
7f7cfc858000-7f7cfc9ed000 r-xp 00000000 08:01 2359317                    /lib/x86_64-linux-gnu/libc-2.24.so
7f7cfc9ed000-7f7cfcbed000 ---p 00195000 08:01 2359317                    /lib/x86_64-linux-gnu/libc-2.24.so
7f7cfcbed000-7f7cfcbf1000 r--p 00195000 08:01 2359317                    /lib/x86_64-linux-gnu/libc-2.24.so
7f7cfcbf1000-7f7cfcbf3000 rw-p 00199000 08:01 2359317                    /lib/x86_64-linux-gnu/libc-2.24.so
7f7cfcbf3000-7f7cfcbf7000 rw-p 00000000 00:00 0
7f7cfcbf7000-7f7cfcc0d000 r-xp 00000000 08:01 2359310                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7cfcc0d000-7f7cfce0c000 ---p 00016000 08:01 2359310                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7cfce0c000-7f7cfce0d000 r--p 00015000 08:01 2359310                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7cfce0d000-7f7cfce0e000 rw-p 00016000 08:01 2359310                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7cfce0e000-7f7cfcf11000 r-xp 00000000 08:01 2359323                    /lib/x86_64-linux-gnu/libm-2.24.so
7f7cfcf11000-7f7cfd110000 ---p 00103000 08:01 2359323                    /lib/x86_64-linux-gnu/libm-2.24.so
7f7cfd110000-7f7cfd111000 r--p 00102000 08:01 2359323                    /lib/x86_64-linux-gnu/libm-2.24.so
7f7cfd111000-7f7cfd112000 rw-p 00103000 08:01 2359323                    /lib/x86_64-linux-gnu/libm-2.24.so
7f7cfd112000-7f7cfd115000 r-xp 00000000 08:01 2359322                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f7cfd115000-7f7cfd314000 ---p 00003000 08:01 2359322                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f7cfd314000-7f7cfd315000 r--p 00002000 08:01 2359322                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f7cfd315000-7f7cfd316000 rw-p 00003000 08:01 2359322                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f7cfd316000-7f7cfd32e000 r-xp 00000000 08:01 2359334                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f7cfd32e000-7f7cfd52d000 ---p 00018000 08:01 2359334                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f7cfd52d000-7f7cfd52e000 r--p 00017000 08:01 2359334                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f7cfd52e000-7f7cfd52f000 rw-p 00018000 08:01 2359334                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f7cfd52f000-7f7cfd533000 rw-p 00000000 00:00 0
7f7cfd533000-7f7cfd636000 r-xp 00000000 08:01 4459384                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f7cfd636000-7f7cfd835000 ---p 00103000 08:01 4459384                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f7cfd835000-7f7cfd838000 r--p 00102000 08:01 4459384                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f7cfd838000-7f7cfd83a000 rw-p 00105000 08:01 4459384                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f7cfd83a000-7f7cfd83b000 rw-p 00000000 00:00 0
7f7cfd83b000-7f7cfd85e000 r-xp 00000000 08:01 2359311                    /lib/x86_64-linux-gnu/ld-2.24.so
7f7cfd86a000-7f7cfd8da000 rw-p 00000000 00:00 0
7f7cfd8da000-7f7cfd97c000 r--p 00000000 08:01 4472704                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.26
7f7cfd97c000-7f7cfd9fb000 r-xp 000a2000 08:01 4472704                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.26
7f7cfd9fb000-7f7cfda3c000 r--p 00121000 08:01 4472704                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.26
7f7cfda3c000-7f7cfda47000 r--p 00161000 08:01 4472704                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.26
7f7cfda47000-7f7cfda4b000 rw-p 0016c000 08:01 4472704                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.26
7f7cfda4b000-7f7cfda50000 rw-p 00000000 00:00 0
7f7cfda5d000-7f7cfda5e000 rw-p 00000000 00:00 0
7f7cfda5e000-7f7cfda5f000 r--p 00023000 08:01 2359311                    /lib/x86_64-linux-gnu/ld-2.24.so
7f7cfda5f000-7f7cfda60000 rw-p 00024000 08:01 2359311                    /lib/x86_64-linux-gnu/ld-2.24.so
7f7cfda60000-7f7cfda61000 rw-p 00000000 00:00 0
7fff3c2d6000-7fff3c2f7000 rw-p 00000000 00:00 0                          [stack]
7fff3c34b000-7fff3c34e000 r--p 00000000 00:00 0                          [vvar]
7fff3c34e000-7fff3c350000 r-xp 00000000 00:00 0                          [vdso]
Aborted (core dumped)
```

**Comment by rouault** [comment]
can you provide the full reproducer (ie with the proj_db[], or an easy way of getting it as a .c file) ?

**Comment by gaoyuanning** [comment]
Sorry, here is an example: https://github.com/gaoyuanning/Proj_Test

**Comment by rouault** [comment]
> Hi rouault, the example code (https://proj.org/en/9.3/development/quickstart.html) will coredump when I try to run it after add `SQLITE_OPEN_URI` flag. I found the coredump triggered in `proj_context_destroy(C)` when we try to destroy the context.

Just an error in your code. You should change freeonclose=1 to freeonclose=0 given that proj_db is a static memory object, that shouldn't be freed

**Pull request merged**
