### PR TITLE
CMake: remove all Mac specific settings added per #2009, …

### LINKED ISSUE #3029: PROJ installs a shared lib with non-empty rpath
#### Example of problem

Build & install proj shared.
Inspect RPATH of the shared lib, for example on macOS, run `otool -l libproj.22.2.1.dylib`.
You'll see absolute paths of external libs in RPATH of proj shared lib.

<details><summary>Click to expand log</summary>

```
libproj.22.2.1.dylib:
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 632
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x00000000002d0000
  fileoff 0
 filesize 2949120
  maxprot 0x00000005
 initprot 0x00000005
   nsects 7
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000000007a00
      size 0x000000000027492f
    offset 31232
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x000000000027c330
      size 0x0000000000000594
    offset 2605872
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __init_offsets
   segname __TEXT
      addr 0x000000000027c8c4
      size 0x0000000000000034
    offset 2607300
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000016
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x000000000027c900
      size 0x0000000000011eae
    offset 2607360
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x000000000028e7b0
      size 0x000000000001e410
    offset 2680752
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000000002acbc0
      size 0x000000000001bd83
    offset 2804672
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x00000000002c8944
      size 0x00000000000076bc
    offset 2918724
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 232
  segname __DATA_CONST
   vmaddr 0x00000000002d0000
   vmsize 0x0000000000018000
  fileoff 2949120
 filesize 98304
  maxprot 0x00000003
 initprot 0x00000003
   nsects 2
    flags 0x10
Section
  sectname __got
   segname __DATA_CONST
      addr 0x00000000002d0000
      size 0x0000000000000b00
    offset 2949120
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 238 (index into indirect symbol table)
 reserved2 0
Section
  sectname __const
   segname __DATA_CONST
      addr 0x00000000002d0b00
      size 0x00000000000168d0
    offset 2951936
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 312
  segname __DATA
   vmaddr 0x00000000002e8000
   vmsize 0x0000000000004000
  fileoff 3047424
 filesize 16384
  maxprot 0x00000003
 initprot 0x00000003
   nsects 3
    flags 0x0
Section
  sectname __data
   segname __DATA
      addr 0x00000000002e8000
      size 0x0000000000000178
    offset 3047424
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x00000000002e8180
      size 0x0000000000001ee0
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x00000000002ea060
      size 0x00000000000014d0
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 3
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x00000000002ec000
   vmsize 0x000000000010c000
  fileoff 3063808
 filesize 1081744
  maxprot 0x00000001
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 4
          cmd LC_ID_DYLIB
      cmdsize 48
         name @rpath/libproj.22.dylib (offset 24)
   time stamp 1 Thu Jan  1 01:00:01 1970
      current version 22.2.1
compatibility version 22.0.0
Load command 5
      cmd LC_DYLD_CHAINED_FIXUPS
  cmdsize 16
  dataoff 3063808
 datasize 23720
Load command 6
      cmd LC_DYLD_EXPORTS_TRIE
  cmdsize 16
  dataoff 3087528
 datasize 91120
Load command 7
     cmd LC_SYMTAB
 cmdsize 24
  symoff 3188880
   nsyms 10286
  stroff 3355816
 strsize 789736
Load command 8
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 7783
     iextdefsym 7783
     nextdefsym 2226
      iundefsym 10009
      nundefsym 277
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 3353456
  nindirectsyms 590
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 9
     cmd LC_UUID
 cmdsize 24
    uuid ECD53939-5CFB-3348-9E31-A03D1A82605A
Load command 10
      cmd LC_BUILD_VERSION
  cmdsize 32
 platform 1
    minos 12.0
      sdk 12.1
   ntools 1
     tool 3
  version 711.0
Load command 11
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1311.0.0
compatibility version 1.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libsqlite3.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libtiffxx.5.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 5.7.0
compatibility version 5.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libtiff.5.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 5.7.0
compatibility version 5.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libdeflate.0.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 17
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/liblzma.5.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 8.5.0
compatibility version 8.0.0
Load command 18
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libjpeg.9.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 14.0.0
compatibility version 14.0.0
Load command 19
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libjbig.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 20
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libzstd.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.5.2
compatibility version 1.0.0
Load command 21
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libwebpdecoder.3.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 3.1.3
compatibility version 3.0.0
Load command 22
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libwebpdemux.2.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 2.0.9
compatibility version 2.0.0
Load command 23
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libwebpmux.3.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 3.0.8
compatibility version 3.0.0
Load command 24
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libwebp.7.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 7.1.3
compatibility version 7.0.0
Load command 25
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libcurl.4.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 12.0.0
compatibility version 12.0.0
Load command 26
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libz.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.2.11
compatibility version 1.0.0
Load command 27
          cmd LC_LOAD_DYLIB
      cmdsize 112
         name /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1163.60.3
compatibility version 1.0.0
Load command 28
          cmd LC_LOAD_DYLIB
      cmdsize 104
         name /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1856.105.0
compatibility version 150.0.0
Load command 29
          cmd LC_LOAD_DYLIB
      cmdsize 96
         name /System/Library/Frameworks/Security.framework/Versions/A/Security (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 60157.60.19
compatibility version 1.0.0
Load command 30
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libc++.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1200.3.0
compatibility version 1.0.0
Load command 31
          cmd LC_RPATH
      cmdsize 112
         path /Users/spaceim/.conan/data/zstd/1.5.2/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib (offset 12)
Load command 32
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/libwebp/1.2.2/_/_/package/6e8cbe983405f952fb58e22087c41f4154ac3259/lib (offset 12)
Load command 33
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/libcurl/7.80.0/_/_/package/6b4c8314e132d9b68b5f48c40d4df883034ce8b3/lib (offset 12)
Load command 34
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/sqlite3/3.37.2/_/_/package/b15b8772d94005922ec8a099e4464c2747b96506/lib (offset 12)
Load command 35
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/libtiff/4.3.0/_/_/package/d3604617558e16293479fa2e12742f04d50430c0/lib (offset 12)
Load command 36
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/libdeflate/1.9/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib (offset 12)
Load command 37
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/xz_utils/5.2.5/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib (offset 12)
Load command 38
          cmd LC_RPATH
      cmdsize 112
         path /Users/spaceim/.conan/data/libjpeg/9d/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib (offset 12)
Load command 39
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/jbig/20160605/_/_/package/880bc78f4d08d85e4d29331704f4c28ea89ee364/lib (offset 12)
Load command 40
          cmd LC_RPATH
      cmdsize 120
         path /Users/spaceim/.conan/data/zlib/1.2.11/_/_/package/bda713dd3b257827c8d11a06ac9d824038871572/lib (offset 12)
Load command 41
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 3178648
 datasize 9632
Load command 42
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 3188280
 datasize 600

```

</details>

#### Problem description

Installed proj shared lib have hardcoded paths to external libs of the build machine. It's not a proper relocatable shared lib, which should have an empty RPATH. It's the default CMake behavior.

It comes from https://github.com/OSGeo/PROJ/pull/2009, and specifically forcing `set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)` which doesn't make sense for a relocatable binary.
But CMake default behavior is already what you would expect: see https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling
Not a good idea usually to enforce babysitting of such thing in CMakeLists, just let people decide externally which behavior they want, so that people can make their own decision of what is a good binary for their specific purpose.

#### Expected Output

Nothing in RPATH of shared lib on *nix systems.

#### Environment Information
 - PROJ since 7.1.0
 - macOS Monterey

#### Installation method
Build from source.

### PR DESCRIPTION
**Pull request by rouault**
…as they apper to be obsolete given current CMake versions (fixes #3029)

And specifically remove set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
which was the only setting at a non-default value.

### CODE REVIEW

**Review by mwtoews — APPROVED** [review]
I would prefer CMake to decide these defaults.

**Comment by dg0yt** [comment]
> I would prefer CMake to decide these defaults.

In addition, this give the user the chance to change it. Before this PR, it would have required patching.

**Comment by kbevers** [comment]
@rouault or @mwtoews please merge this is you think is good to go. Release candidate is coming up and this would be great to include!

**Comment by rouault** [comment]
merged

**Pull request merged**
