### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by rouault**
Question: should we keep the mispelled PJD_ERR_UNKNOW_UNIT_ID in projects.h ?

### CODE REVIEW

**Comment by rouault** [comment]
OK, mispelled #defined removed per 290834e

**Comment by kbevers** [comment]
> OK, mispelled #defined removed per 290834e

I probably wasn't very clear before. What I meant was that keeping both the misspelled and the correctly spelled constant would be best until we remove `projects.h`. We'll release 5.1 and 5.2 before 6.0 so theoretically we're are changing public API without a bump of major version number. It is extremely unlikely to cause problems but you never know what's going on out there :-)

**Comment by rouault** [comment]
@kbevers OK, I just cancelled the last commit that removed the misspelled constant.

**Comment by kbevers** [comment]
Thanks!

**Pull request merged**
