### PR TITLE
Improve Visual Studio compatibility check in CMake.

### PR DESCRIPTION
**Pull request by cffk**
Make the setting of major toolset version variables parallel that for
cross-compilation.  Add comments so it's easier for the next person
looking at this code to figure what's going on.  Note: no need to unset
variables at the end of the version check file (the file is read in a
nested scope).

### CODE REVIEW

**Comment by cffk** [comment]
I assume the build failure is some transient problem.  Is there some way (other that forcing a new commit) to trigger the checks again?

**Comment by snowman2** [comment]
> I assume the build failure is some transient problem. Is there some way (other that forcing a new commit) to trigger the checks again?

You can close and reopen the PR.

**Comment by cffk** [comment]
Try checks again.

**Comment by rouault** [comment]
I've manually restarted the job

**Comment by rouault** [comment]
It seems there has been an upgrade in the version of sphinxcontrib-bibtex available in pip, which is installed per travis/linux_gcc/before_install.sh.
The last successful build https://api.travis-ci.com/v3/job/237477314/log.txt used sphinxcontrib_bibtex-0.4.2-py2.py3-none-any.whl which installed Sphinx-1.8.5-py2.py3-none-any.whl.
The failed build installs sphinxcontrib_bibtex-1.0.0-py3-none-any.whl which requires Sphinx >= 2.0, but the later requires Python 3.5, whereas Trusty has only Python 3.4
So the easiest solution I think would be to modify travis/linux_gcc/before_install.sh to do `pip3 install --user sphinxcontrib-bibtex==0.4.2` . Or find a way of using a newer Python version

**Comment by rouault** [comment]
@cffk  Yes it didn't work because the commit added a new command 2 lines after the faulty line at line 18, instead of just modifying the faulty one. Sorry for not having been clearer.

**Comment by rouault** [comment]
I'll try the fix in another pull request, since that will need to be backported to 6.2

**Comment by rouault** [comment]
Potential fix for sphinx issue in https://github.com/OSGeo/PROJ/pull/1627

**Comment by cffk** [comment]
@rouault Ah, sorry, I just blindly added the extra line.  I'll wait for you pull request to be merged and then resubmit.

**Comment by rouault** [comment]
> I'll wait for you pull request to be merged

Done. You can rebase on top of updated master

**Comment by rouault** [comment]
@cffk In those circumstances with a git history with trials & errors, I would suggest a git rebase -i to improve a bit the commit history.

**Comment by cffk** [comment]
OK, thanks for the tip.  I got into the habit of making pedestrian updates to git after being burned in my early days of git usage by incompetently backing out of changes.

**Comment by rouault** [comment]
you can always do a "git checkout -b mybackup_branch" before doing potential destructive changes

**Pull request merged**
