### PR TITLE
Fix cmake CURL dependency, update appveyor - vcpkg interaction

### PR DESCRIPTION
**Pull request by dg0yt**
Includes #3169.

 - [X] Ensure consistent and proper vcpkg usage
 - [X] Added clear title that can be used to generate release notes

### CODE REVIEW

**Comment by dotlambda** [comment]
Because of this change the following ends up in `/lib/cmake/proj4/proj4-config.cmake`:
```cmake
include(CMakeFindDependencyMacro)
if("TRUE" STREQUAL "TRUE")
  # Chainload CURL usage requirements
  find_dependency(CURL)
endif()
```
This means that anything using `find_package(PROJ4 REQUIRED)` now also depends on cURL. Is that intentional?

**Comment by dg0yt** [comment]
> This means that anything using `find_package(PROJ4 REQUIRED)` now also depends on cURL. Is that intentional?

Anything which depends on a build of PROJ which is configured with CURL. Note that the source is:
https://github.com/OSGeo/PROJ/blob/65458dfb8123a96ccd45a46c363e81e1307c1582/cmake/project-config.cmake.in#L15-L18

**Comment by dotlambda** [comment]
> Anything which depends on a build of PROJ which is configured with CURL.

You're right. But I don't quite see why a project depending on PROJ (configured with cURL) should depend on cURL. Does the latter need to be available at link time?

**Comment by dg0yt** [comment]
> But I don't quite see why a project depending on PROJ (configured with cURL) should depend on cURL. 

It does so anyways, at least transitively.

> Does the latter need to be available at link time?

At least it is needed at CMake configuration time, in order to resolve the dependencies CURL implies for generated PROJ config.  Cf. https://github.com/OSGeo/PROJ/pull/3169#issuecomment-1104846458.
(There might be better decoupling at least for dynamic linkage, but it would need to start at CURL.)

**Comment by rouault** [comment]
> (There might be better decoupling at least for dynamic linkage, but it would need to start at CURL.)

coulnd't we just make the find_dependency(CURL) conditioned by BUILD_SHARED_LIBS being set ?

**Comment by dg0yt** [comment]
> > (There might be better decoupling at least for dynamic linkage, but it would need to start at CURL.)
> 
> coulnd't we just make the find_dependency(CURL) conditioned by BUILD_SHARED_LIBS being set ?

First you have to update CURL, to make it link `CURL_LIBS` privately:
https://github.com/curl/curl/blob/8dcbb0f19176da937ddb3c85509b8c84086348f1/lib/CMakeLists.txt#L98
But now the public dependencies are already out in the wild.

**Pull request merged**
