### PR TITLE
Repairing tests that fails on OS X

### PR DESCRIPTION
**Pull request by kbevers**
As described in #468 and #469 

All tests but the one for ```pipeline``` can be fixed by using ```+R``` instead of ```+a```. I suspect this was caused by refactoring the ellipsoid-code in 44c611c. Is that correct, @busstoptaktik?

The ```pipeline``` test fails because the expected tolerance of 1e-4 is not met. Instead it comes out as 0.000124169332, which is close but not quite there. I don't know why that happens. The problem is easily solved by changing the tolerance, but before we go down that path we should try to find an explanation as to why the results differ across system.

### CODE REVIEW

**Comment by kbevers** [comment]
For the record, the test output is now:

```
$ ./proj -VC
Running internal regression tests
Testing:        aea - return code: 0
Testing:       aeqd - return code: 0
Testing:       airy - return code: 0
Testing:     aitoff - return code: 0
Testing:       alsk - return code: 0
Testing:      apian - return code: 0
Testing:     august - return code: 0
Testing:      bacon - return code: 0
Testing:       bipc - return code: 0
Testing:      boggs - return code: 0
Testing:      bonne - return code: 0
Testing:    calcofi - return code: 0
Testing:       cart - return code: 0
Testing:       cass - return code: 0
Testing:         cc - return code: 0
Testing:        cea - return code: 0
Testing:      chamb - return code: 0
Testing:      collg - return code: 0
Testing:     comill - return code: 0
Testing:      crast - return code: 0
Testing:      denoy - return code: 0
Testing:       eck1 - return code: 0
Testing:       eck2 - return code: 0
Testing:       eck3 - return code: 0
Testing:       eck4 - return code: 0
Testing:       eck5 - return code: 0
Testing:       eck6 - return code: 0
Testing:        eqc - return code: 0
Testing:       eqdc - return code: 0
Testing:      euler - return code: 0
Testing:     etmerc - return code: 0
Testing:      fahey - return code: 0
Testing:       fouc - return code: 0
Testing:     fouc_s - return code: 0
Testing:       gall - return code: 0
Testing:    geocent - return code: 0
Testing:       geos - return code: 0
Testing:      gins8 - return code: 0
Testing:    gn_sinu - return code: 0
Testing:       gnom - return code: 0
Testing:      goode - return code: 0
Testing:       gs48 - return code: 0
Testing:       gs50 - return code: 0
Testing:     hammer - return code: 0
Testing:     hatano - return code: 0
Testing:    healpix - return code: 0
Testing:   rhealpix - return code: 0
Testing:    helmert - return code: 0
Testing:     horner - return code: 0
Testing:        igh - return code: 0
Testing:      imw_p - return code: 0
Testing:       isea - return code: 0
Testing:       kav5 - return code: 0
Testing:       kav7 - return code: 0
Testing:     krovak - return code: 0
Testing:      labrd - return code: 0
Testing:       laea - return code: 0
Testing:     lagrng - return code: 0
Testing:       larr - return code: 0
Testing:       lask - return code: 0
Testing:     lonlat - return code: 0
Testing:     latlon - return code: 0
Testing:    latlong - return code: 0
Testing:    longlat - return code: 0
Testing:        lcc - return code: 0
Testing:       lcca - return code: 0
Testing:       leac - return code: 0
Testing:     lee_os - return code: 0
Testing:      loxim - return code: 0
Testing:       lsat - return code: 0
Testing:      mbt_s - return code: 0
Testing:    mbt_fps - return code: 0
Testing:     mbtfpp - return code: 0
Testing:     mbtfpq - return code: 0
Testing:     mbtfps - return code: 0
Testing:       merc - return code: 0
Testing:     mil_os - return code: 0
Testing:       mill - return code: 0
Testing:    misrsom - return code: 0
Testing:       moll - return code: 0
Testing:      murd1 - return code: 0
Testing:      murd2 - return code: 0
Testing:      murd3 - return code: 0
Testing:   natearth - return code: 0
Testing:  natearth2 - return code: 0
Testing:       nell - return code: 0
Testing:     nell_h - return code: 0
Testing:      nicol - return code: 0
Testing:      nsper - return code: 0
Testing:       nzmg - return code: 0
Testing:    ob_tran - return code: 0
Testing:       ocea - return code: 0
Testing:        oea - return code: 0
Testing:      omerc - return code: 0
Testing:      ortel - return code: 0
Testing:      ortho - return code: 0
Testing:     pconic - return code: 0
Testing:  patterson - return code: 0
Testing:   pipeline - return code: 1001
Testing:       poly - return code: 0
Testing:      putp1 - return code: 0
Testing:      putp2 - return code: 0
Testing:      putp3 - return code: 0
Testing:     putp3p - return code: 0
Testing:     putp4p - return code: 0
Testing:      putp5 - return code: 0
Testing:     putp5p - return code: 0
Testing:      putp6 - return code: 0
Testing:     putp6p - return code: 0
Testing:    qua_aut - return code: 0
Testing:        qsc - return code: 0
Testing:      robin - return code: 0
Testing:      rouss - return code: 0
Testing:      rpoly - return code: 0
Testing:        sch - return code: 0
Testing:       sinu - return code: 0
Testing:     somerc - return code: 0
Testing:      stere - return code: 0
Testing:     sterea - return code: 0
Testing:    gstmerc - return code: 0
Testing:        tcc - return code: 0
Testing:       tcea - return code: 0
Testing:      times - return code: 0
Testing:     tissot - return code: 0
Testing:      tmerc - return code: 0
Testing:      tpeqd - return code: 0
Testing:      tpers - return code: 0
Testing:        ups - return code: 0
Testing:       urm5 - return code: 0
Testing:     urmfps - return code: 0
Testing:        utm - return code: 0
Testing:      vandg - return code: 0
Testing:     vandg2 - return code: 0
Testing:     vandg3 - return code: 0
Testing:     vandg4 - return code: 0
Testing:      vitk1 - return code: 0
Testing:       wag1 - return code: 0
Testing:       wag2 - return code: 0
Testing:       wag3 - return code: 0
Testing:       wag4 - return code: 0
Testing:       wag5 - return code: 0
Testing:       wag6 - return code: 0
Testing:       wag7 - return code: 0
Testing:      weren - return code: 0
Testing:      wink1 - return code: 0
Testing:      wink2 - return code: 0
Testing:     wintri - return code: 0
[Stubs: 0]          Total: 147. Failure: 1. Success: 146
```

**Comment by busstoptaktik** [comment]
A couple of random thoughts:

**Regarding the ellipsoid/sphere problem:**

I do not have access to an OS/X system, so I cannot test this. But I find it strange that the ellipsoid/sphere difference shows up in the OS/X cases only: The ellipsoid/sphere bug is tripped by the `<general>` section in `nad/proj_def.dat`, with its `ellps=WGS84` incantation adding the eccentricity of the WGS84 ellipsoid to the list of args processed by pj_init. This should affect all platforms identically.


**The pipeline regression:**

The `+proj=pipeline` regression test failing is quite strange. The 1001 test case is a straightforward utm-roundtrip for a point exactly on the border between zone 32 and zone 33. The Engsager/Poder/Karney implementation of the transverse mercator projection should be able to roundtrip way better than that even far longer from the center meridian.

The roundtrip precision is gauged by calling `pj_lp_dist` which, in turn, calls the `geod_inverse` function from the new geodesic library by @cffk. This library is supposed to be extremely precise, even for very long geodesics, and works around a number of  numerical gotchas from the older version. I assumed that it would also be precise for very short (< 0.1 mm) geodesics, but I haven't attempted to confirm this. And still: it seems to be a OS/X specific thing.

@kbevers: Could you do a 15 decimal places dump of the contents of `a.coo.lp, b.coo.lp` in line 539 of 
`PJ_pipeline.c` under OS/X? It could give some insight about where to continue the search.

I think that the OS/X handling of the math library is special, but I do not know in which sense. Could this influence the result?

Seriously puzzled!

**Comment by kbevers** [comment]
>Regarding the ellipsoid/sphere problem:
>
>I do not have access to an OS/X system, so I cannot test this. But I find it strange that the ellipsoid/sphere difference shows up in the OS/X cases only: The ellipsoid/sphere bug is tripped by the <general> section in nad/proj_def.dat, with its ellps=WGS84 incantation adding the eccentricity of the WGS84 ellipsoid to the list of args processed by pj_init. This should affect all platforms identically.

It would seem that it doesn't. Why that is I don't know. I only looked at a few test results and if I remember correctly the expected and calculated coordinates were not just differing on the last few decimals. I would say that rules out some small numerical discrepancies on OS X vs. everything else. My best guess is that some of the defines regarding math constants are not properly applied on OS X.

> @kbevers: Could you do a 15 decimal places dump of the contents of a.coo.lp, b.coo.lp in line 539 of
PJ_pipeline.c under OS/X? It could give some insight about where to continue the search.

I will do that tonight when I have access to a Mac.

**Comment by kbevers** [comment]
@busstoptaktik as you requested:
```
538     b = pj_trans (P, PJ_FWD, a);
539     if (pj_lp_dist (P, a.coo.lp, b.coo.lp) > 1e-4) {
540         printf("a.coo.lp = (%15.15g, %15.15g)\n", a.coo.lp.lam, a.coo.lp.phi);
541          printf("b.coo.lp = (%15.15g, %15.15g)\n", b.coo.lp.lam, b.coo.lp.phi);
542         return 1001;
543     }
```

which returns:
```
a.coo.lp = (0.20943951023932,  0.959931088596881)
b.coo.lp = (0.209439510238445, 0.95993108857742)
```

The coordinates differ at the 10-11th decimal. I wouldn't expect that to fail.

**Comment by kbevers** [comment]
From the command line I get a difference of 0.000002168544754 between the two points: 
```
echo 0.20943951023932 0.959931088596881 0.209439510238445 0.95993108857742 | geod -I -F %15.15f +ellps=WGS84
-92d33'25.855"	87d26'34.145"	0.000002168544754
```
So probably not a bug in gegraphiclib.

**Comment by kbevers** [comment]
Using
```
+proj=pipeline +zone=32 +step +proj=utm +ellps=GRS80 +step +proj=utm +ellps=GRS80 +inv"
```
insted of
```
+proj=pipeline +ellps=GRS80 +zone=32 +step +proj=utm +step +proj=utm +inv"
```
seem to have fixed the problem with the pipeline test. Why it works on Windows+Linux and not on OSX is unclear to me. It is likely that there is a bug with regards to using "global" +parameters in pipelines

**Comment by kbevers** [comment]
@busstoptaktik unless you have an issue with this solution I'm going to merge this soon so @rouault  can get on with #468

**Comment by busstoptaktik** [comment]
Merge as you please. I'll look into the underlying problem as soon as time
permits, but having neither osx experience, nor osx access, I may need some
help from more "osxperienced" people.

Den 18. jan. 2017 10.27 PM skrev "Kristian Evers" <notifications@github.com

**Pull request merged**
