### PR TITLE
Add Belgian geoid model hBG18 to grid alternatives

### PR DESCRIPTION
**Pull request by AlexBass05**
Corresponding PR in PROJ-data: https://github.com/OSGeo/PROJ-data/pull/77

Created as a draft PR as it requires an EPSG database update to include this change request: https://epsg.org/closed-change-request/browse/id/2022.007

### CODE REVIEW

**Comment by rouault** [comment]
I've rebased your PR on top of #3051 which updates to EPSG v10.054

Things seem to work fine:
```
$ echo "50 5 0" | PROJ_NETWORK=ON PROJ_DEBUG=2 PROJ_LIB=data bin/cs2cs EPSG:4937 EPSG:9907
[...]
Using https://cdn.proj.org/be_ign_hBG18.tif
50.00	5.00 -44.32
```

**Comment by kbevers** [comment]
@rouault is this (and the corresponding PROJ-data PR) ready to merge? I'm gearing up for the release candidate and want to merge as much as possible. If possible I'd like to do the RC tomorrow afternoon (DK time).

**Comment by rouault** [comment]
merged

**Comment by AlexBass05** [comment]
> I've rebased your PR on top of #3051 which updates to EPSG v10.054
> 
> Things seem to work fine:
> 
> ```
> $ echo "50 5 0" | PROJ_NETWORK=ON PROJ_DEBUG=2 PROJ_LIB=data bin/cs2cs EPSG:4937 EPSG:9907
> [...]
> Using https://cdn.proj.org/be_ign_hBG18.tif
> 50.00	5.00 -44.32
> ```

Excellent! Thanks a lot for the rebase and the merge.
Testing on my side also indicates that things work fine.

**Pull request merged**
