### PR TITLE
Pushing fix for thread safety issue 478

### PR DESCRIPTION
**Pull request by paulhanssen**
Hi,

I'm from the same company as the person that raised the issue in https://github.com/OSGeo/proj.4/issues/478.

This is our fix for it ... it compiles and runs "make tests" successfully.

Hope it helps.

### CODE REVIEW

**Comment by rouault** [comment]
Apparently it fails the multithreading stress test:
```
Segmentation fault      (core dumped) PROJ_LIB=../nad src/multistresstest
```

**Comment by kbevers** [comment]
@paulhanssen Have you lost interest in this, or do you want to try to fix the problem pointed out by the tests?

**Comment by paulhanssen** [comment]
Hi @kbevers I did not make this change, only pushed the pull request, but let me try giving it a go over the next week.

**Comment by kbevers** [comment]
Cool, thanks!

**Comment by liuj03** [comment]
I wrote the fix originally.

We were trying to call pj_transform on the same projPJ instance from multiple threads. But encountered a race condition which caused pj_transform to crash.

https://github.com/OSGeo/proj.4/issues/478

Our previous workaround was to mutex every call to proj4, which eventually became too big a bottleneck.

The fix appears to have resolved the race condition and crash is no longer happening. But I may not have sufficient understanding of proj4 to ensure all cases are covered.

Is the latest version of proj4 able to handle multiple calls to pj_transform on the same projPJ instance from multiple threads?

**Comment by kbevers** [comment]
> Is the latest version of proj4 able to handle multiple calls to pj_transform on the same projPJ instance from multiple threads?

You shouldn't do that, no. I understand what you were trying to do, and appreciate that you have a working setup in your environment, but if we are to merge this change at least the continuous integration tests should pass. They don't at the moment. 

If you don't want to pursue a fix that passes our tests, then that is perfectly fine. If so, let me know and I'll close this PR.

**Comment by liuj03** [comment]
What is the correct way to call pj_transform from multiple threads?
Do I need to have a separate instance of projPJ per thread?

**Comment by busstoptaktik** [comment]
In brief: Yes.

A little less brief: I think it has never been discussed in public, but
apparently, the "context" element of proj has to do with thread safety
(albeit in ways that are not totally clearly described or argued), and each
PJ object is connected to a specific context (which may be shared among
many PJs)

In the OBS API, which I am currently developing (cf. pj_obs_api.c and
proj.h), one of the intentions is to make this more clear (an upcoming PR
will address this in more depth).

A major problem in touching the proj context related code is that it is not
really clear who uses it, hence very hard to devise evolutionary paths that
do not interfere with established use cases.

/thomas


2017-06-02 11:24 GMT+02:00 Jason Liu <notifications@github.com>:

**Comment by busstoptaktik** [comment]
Closing, as this is likely only relevant for the use case in operation in the project by @paulhanssen  and @liuj03 (see comments above regarding why)

@paulhanssen  and @liuj03: If you believe closing is wrong, please reopen, and explain why

**Pull request closed without merging**
