### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by jidanni**
- [ ] Closes #xxxx
 - [ ] Tests added
 - [ ] Added clear title that can be used to generate release notes
 - [ ] Fully documented, including updating `docs/source/*.rst` for new API

### CODE REVIEW

**Comment by jidanni** [comment]
Please fix this for both the proj and cs2cs man pages.

**Comment by kbevers** [comment]
> Please fix this for both the proj and cs2cs man pages.

Why don't you just add those fixes as well?

**Comment by jidanni** [comment]
I am barely sure that I edited the right page,
and I cannot be sure what the exact other pages are.

There seems to be a single boilerplate, that should be edited somewhere.
And this boilerplate ends up on templates.
And these templates get converted into man pages.

**Comment by kbevers** [comment]
You got the right file.  The rest will be in `docs/source/apps/` apptly named by the application they document. At release time these are used to generate fresh man pages. The website is update as soon as changes are merged into the currently active maintenance branch.

**Comment by rouault** [comment]
Superseded per https://github.com/OSGeo/PROJ/pull/2613

**Pull request closed without merging**
