### PR TITLE
Incorrect EPGS extent code for EPSG:7789>EPSG:4976 NKG transformation

### PR DESCRIPTION
**Pull request by himsve**
- [x] Added clear title that can be used to generate release notes

### CODE REVIEW

**Review by kbevers — APPROVED** [review]

**Comment by rouault** [comment]
Remvoving the backport label: it is not appropriate here as the initial addition is in master only

**Comment by kbevers** [comment]
@rouault the bug is also present in the 8.0 branch as seen her:

 https://github.com/OSGeo/PROJ/blob/8e9239cfe4045a638d0f9e018cdb7d3f3f9622a5/data/sql/nkg.sql#L2156-L2162

but it may be the case that the fix won't merge easily because of the added Norwegian transformations to the `nkg.sql` file.

**Comment by rouault** [comment]
>  the bug is also present in the 8.0 branch as seen her:

oops my bad. I guess I was confused with the recent Norwegian's additions... Re-adding backport label :-)

**Comment by kbevers** [comment]
I understand. The additions in #2548 should probably also be backported, there's no real reason for not doing so I think. Agree?

**Comment by rouault** [comment]
> The additions in #2548 should probably also be backported, there's no real reason for not doing so I think. Agree?

Should be OK, but https://github.com/OSGeo/PROJ/commit/e10a849cd01c5b15e3123da1f6df845006322843 needs also to be backported, as #2548 without it was broken for NKG transformations.

**Comment by rouault** [comment]
There's also a version number and release dates in nkg.sql which haven't been updated since its initial version in 8.0

**Comment by himsve** [comment]
It's seems that the NKG::ITRF2014_TO_SE's in NKG.gie have failed. I was not awared that the gie tests were influed by the extent code fix. It may be fixed.

**Comment by rouault** [comment]
> It's seems that the NKG::ITRF2014_TO_SE's in NKG.gie have failed. I was not awared that the gie tests were influed by the extent code fix. It may be fixed.

The failures I see are:
```
$ PROJ_LIB=$HOME/proj/PROJ-data/eur_nkg:$HOME/proj/PROJ-data/se_lantmateriet:$HOME/proj/PROJ-data/no_kv:data src/gie ../test/gie/nkg.gie 
-------------------------------------------------------------------------------
Reading file '../test/gie/nkg.gie'
xyzgridshift: could not find required grid(s).
pipeline: Pipeline: Bad step definition: proj=xyzgridshift (File not found or invalid)
     -----
     FAILURE in nkg.gie(211):
     expected: 3275753.9111 321110.8658 5445041.8822 2020.0
     got:      inf   inf   inf   inf
     deviation:  999999999.999000 mm,  expected:  0.100000 mm
     -----
     FAILURE in nkg.gie(215):
     expected: 2391774.5535 615614.9100 5860965.8138 2020.0
     got:      inf   inf   inf   inf
     deviation:  999999999.999000 mm,  expected:  0.100000 mm
     -----
     FAILURE in nkg.gie(219):
     expected: 2107889.5097 895603.2085 5933242.3152 2020.0
     got:      inf   inf   inf   inf
     deviation:  999999999.999000 mm,  expected:  0.100000 mm
-------------------------------------------------------------------------------
total: 28 tests succeeded,  0 tests skipped,  3 tests FAILED!
-------------------------------------------------------------------------------
```

The reason seems to be related to no_kv_NKGETRF14_EPSG7922_2000.tif having not being yet included in PROJ-data, but referenced by the NKG:NKG_ETRF14_ETRF93_2000 operation, which is itself used as a step of the NKG::ITRF2014_TO_NO concatenated operation

**Comment by himsve** [comment]
Sorry about the failed GIE test I reported. I was running the test with an unofficial resource file 👍

**Comment by rouault** [comment]
> Sorry about the failed GIE test I reported. I was running the test with an unofficial resource file

hum, but the failed gie test does report a real issue: nkg.sql references a file not in PROJ-data

**Pull request merged**
