### PR TITLE
Add a CMake EMBED_GRIDS_DIRECTORY option to embed .tif/.json files in to libproj

### PR DESCRIPTION
**Pull request by rouault**
and also generalize the existing EMBED_RESOURCE_FILES option to embed the ITRFxxxx resource files.

```
.. option:: EMBED_GRIDS_DIRECTORY=<directory>

    .. versionadded:: 9.6

    Embed files from <directory> ending with .tif or .json in the PROJ library itself.

    The pointed directory can potentially be the full PROJ-data package (uncompressed).
    In that case, about 6 GB of free disk and 16 GB of RAM are required to build PROJ.

    When using this parameter, EMBED_RESOURCE_FILES must be set to ON.

    If the content of the directory changes, you need to run CMake again to
    update the list of files.
```

### CODE REVIEW

**Comment by hobu** [comment]
All-or-nothing for now, but would you expect to allow configuration of which grids should be embedded?

**Comment by rouault** [comment]
> All-or-nothing for now, but would you expect to allow configuration of which grids should be embedded?

why not just creating a directory containing all grids you are interested in ? Pointing at individual files with CMake options could be tedious, couldn't it?

**Comment by hobu** [comment]
> why not just creating a directory containing all grids you are interested in ? Pointing at individual files with CMake options could be tedious, couldn't it?

Fair point, although I was thinking about standard distribution situations like a widely distributed WASM PROJ with embedded resources on cdn.proj.org. Maybe that's always every grid file...

**Comment by willcohen** [comment]
My work-in-progress WASM proj could be a good candidate for this (though, to be clear, it's still squarely in javascript+wasm land because of needing to handle the malloc and freeing of objects via the C api -- https://github.com/OSGeo/PROJ/issues/4327). It'll prob be a little while before I stabilize enough to throw all the grid files in there, but I could imagine there being, effectively, two different distributions of WASM PROJ, one ~10-20MB one where it's the library + DB (size dependent on whether it's base64'd into a JS file, as is the case right now), or a mega one for people who are going for full-intensity projections.

**Pull request merged**
