### PR TITLE
Add BETA2007 grid and change potsdam datum

### PR DESCRIPTION
**Pull request by rouault**
Functionnaly equivalent to https://github.com/OSGeo/proj.4/pull/371 by Jürgen Fischer

See
http://crs.bkg.bund.de/crseu/crs/descrtrans/BeTA/de_dhdn2etrs_beta.php

Confirmed with Uwe Schmitz uwe.schmitz@bezreg-koeln.nrw.de that free
redistribution is allowed and welcome.

### CODE REVIEW

**Comment by rouault** [comment]
@jef-n In your initial PR (https://github.com/OSGeo/proj.4/pull/371), you only altered EPSG:31461 to 31469 to use the BETA2007.gsb, but I guess that all other SRS that refer to datum=potsdam should also use it ? (as done in this PR)

**Comment by jef-n** [comment]
AFAIK this is only commonly used in the context of transforming data in 31466-9 (DHDN/GK) to 25832/3 (UTM).  Not sure about other cases.

**Comment by rouault** [comment]
The other CRS that use potsdam are:

```
<4314> +proj=longlat +datum=potsdam +no_defs  <>
<3068> +proj=cass +lat_0=52.41864827777778 +lon_0=13.62720366666667 +x_0=40000 +y_0=10000 +datum=potsdam +units=m +no_defs  <>
<5520> +proj=tmerc +lat_0=0 +lon_0=3 +k=1 +x_0=1500000 +y_0=0 +datum=potsdam +units=m +no_defs  <>
<5676> +proj=tmerc +lat_0=0 +lon_0=6 +k=1 +x_0=2500000 +y_0=0 +datum=potsdam +units=m +no_defs  <>
<5677> +proj=tmerc +lat_0=0 +lon_0=9 +k=1 +x_0=3500000 +y_0=0 +datum=potsdam +units=m +no_defs  <>
<5678> +proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +y_0=0 +datum=potsdam +units=m +no_defs  <>
<5679> +proj=tmerc +lat_0=0 +lon_0=15 +k=1 +x_0=5500000 +y_0=0 +datum=potsdam +units=m +no_defs  <>
<5680> +proj=tmerc +lat_0=0 +lon_0=3 +k=1 +x_0=1500000 +y_0=0 +datum=potsdam +units=m +no_defs  <>
```

Given that by default, in current proj, +datum=potsdam expands to +ellps=bessel +towgs84=598.1,73.7,418.2,0.202,0.045,-2.455,6.7, which must be an approximation of the BETA2007.gsb grid since the grid is applied to many UTM zones, I believe it wouldn't hurt to apply the grid to all CRS that refer to Potsdam ? (if not, that's going to be messy to support that properly. Would probably requre a hack somewhere in GDAL epsg_tr.py mechanism so that it generates the 'espg' file with the override only for the 31466-9 (DHDN/GK)  )

**Comment by bastik** [comment]
I can confirm, that for all the listed CRS with datum "potsdam" it would be correct to use the BETA2007 grid transformation.

All of them are based on the "Deutsche Hauptdreiecksnetz" (DHDN) datum which is a triangulation network created in the second half of the 19th century and still in use today, alongside modern global systems. The current 7-parameter transformation is an approximation at 3 meter level. "Potsdam" refers to the current fundamental point.

In particular, 5676-5679 are the same CRS as 31466-31469, but with x- and y-axis switched. 4314 is just the DHDN and 3068 another projection based on DHDN.

**Comment by busstoptaktik** [comment]
@bastik asserts this PR should be merged, but since it would change DHDN based transformations at the meter level, it will probably also cause problems for someone if done without warning.

So @rouault and @jef-n, while merging is definitely the right thing to do, I think this should probably be aired on the mailing list beforehand. Do you agree, and would one of you write up a message?

**Comment by busstoptaktik** [comment]
Having re-read this discussion in the light of more recent discussion over at #708, I think this really should be merged as part of the 5.0.0.RC2 work:.

Compared to the Australian grids of 70 MB, the BETA2007 grid is tiny (80 kB), so for two reasons, I think it should be merged directly to PROJ in its entirety, rather than split in a code commit here and a grid commit over at datumgrids:

1. The geodetic reason: To update the existing deprecated Helmert shift, and provide some better material.
2. The software engineering reason: To provide a built-in data target for authoring additional tests.

My German is slightly rusty, but I think, following [this](https://forum.openstreetmap.org/viewtopic.php?id=12723) OSM discussion, [this](http://crs.bkg.bund.de/crseu/crs/descrtrans/BeTA/de_dhdn2etrs_beta.php) excellent description from BKG (the German federal mapping agency), and [this](crs.bkg.bund.de/crseu/crs/descrtrans/BeTA/BETA2007testdaten.csv) related set of test points, the conclusion is that the current PROJ implementation of DHDN/Potsdam is *broken* and we *should* repair it by providing the BeTA grid.

I *do* however, also believe we should provide test cases (based on the BKG list), and provide a temporary fallback possibility, by keeping the old potsdam definition under the name `potsdam_deprecated`, so anyone needing the backwards compatibility can get it by manually patching their epsg file. @bastik, @jef-n, @kbevers , and @rouault: Do you agree?

The original work by @rouault is already 20 months old, and 600 commits behind of master. The changes are, however, small, and surprisingly, it appears to be possible to cleanly merge and/or rebase.

Despite also mostly agreeing with @kbevers remark regarding the problems with the `+datum=...` notation, I would like to give it a try, adding the potsdam_deprecated, and a `gie` test suite, but it's getting late, so that will be a thing for tomorrow.

**Comment by rouault** [comment]
No opposition from me to merge this

**Comment by kbevers** [comment]
+0 from me. 

Regarding `+datum=potsdam_deprecated`, should anyone wish to continue using the faulty 7 parameter shift they can patch their epsg-file with `+towgs84=598.1,73.7,418.2,0.202,0.045,-2.455,6.7`. A note about this can be written in the release notes or FAQ.

**Comment by busstoptaktik** [comment]
Merging this locally, and adding support for the official BKG test material, revealed a number of bugs in various subsystems, which I have corrected.

The PR itself is fine - it just supports adding some test material that reveals imperfections elsewhere.

So I will merge this now, and provide a PR with extensive follow up work in a few hours.

**Comment by sebastic** [comment]
While `nad/BETA2007.gsb` is included in the git repository, the proj tarballs don't actually contain the file.

None of the .gsb files are included in the proj tarball, they are included in the proj-datumgrid archive.

**Comment by kbevers** [comment]
For this release I will make sure that the BETA2007 grid is added to the PROJ tarball. I agree that we should move all grids from this repo and over to the datumgrid repo instead. It will be a thing for a later release. Probably 6.0.0, since it is a big change and we need a bit of time to think it through properly.

**Comment by sebastic** [comment]
> While nad/BETA2007.gsb is included in the git repository, the proj tarballs don't actually contain the file.

This is still the case in RC4.

**Comment by sebastic** [comment]
> Confirmed with Uwe Schmitz [uwe.schmitz@bezreg-koeln.nrw.de](mailto:uwe.schmitz@bezreg-koeln.nrw.de) that free redistribution is allowed and welcome.

But does it also allow modification?

**Comment by rouault** [comment]
@jef-n I see you were the initial submitter for the BETA2007 grid. Would you mind contacting the producer (uwe.schmitz@bezreg-koeln.nrw.de) to see if they can provide more standard licensing terms than just "free redistribution is allowed and welcome." In particular we'd need a mention that modifications are allowed. A reasonable resolution I guess would be that they use the "Data licence Germany - attribution - version 2.0" as used by other Länders (Baden-Württemberg, Sachsen) or Creative Commons Attribution 4.0 as used by Saarland.

**Comment by jef-n** [comment]
Mail sent.

**Comment by jef-n** [comment]
Response:
```
From uwe.schmitz@bezreg-koeln.nrw.de  Tue Feb 25 11:28:39 2020
From: "Schmitz, Uwe" <uwe.schmitz@bezreg-koeln.nrw.de>
To: "Jürgen E. Fischer" <jef@norbit.de>
Subject: Re: Weiterverteilung von der BETA2007-Grid
Date: Tue, 25 Feb 2020 10:09:48 +0000

Hallo Herr Fischer,

leider hat man es damals bei der Spezifikation von
BeTA2007 versäumt ein entsprechende Lizenz für
den Parametersatz zu vergeben. Evtl. kann man dies
im Nachhinein noch durch die Gremien der AdV
veranlassen, aber die Mühlen mahlen langsam.
Bis dahin betrachte ich mich als Lizenzvertreter
und versuche Ihre Frage zu beantworten.

Die Intention bei BeTA2007 war es, eine möglichst freie
Nutzung, ohne Einschränkung auf nicht kommerzielle Gebiete,
zuzulassen.

Die BeTA2007 Gitterdatei kann zur direkten Nutzung in
andere Software eingebunden bzw. zum Download angeboten werden.
Eine Namensnennung ist gewünscht. Auch einer Formatänderung,
sofern der ursprüngliche Genauigkeitsanspruch gewahrt bleibt,
steht nichts im Wege. Bei einer inhaltlichen Änderung/Erweiterung
darf der Name BeTA2007 nicht mehr weiter verwendet werden.
Das abgeleitete Produkt sollte dann über einen entsprechenden
Vermerk den Bezug herstellen.

Ich hoffe, diese Aussage reicht Ihnen.
Viele Grüße
Uwe Schmitz
```

So: The license wasn't outlined in the initial specification and adding it now would take time, until then Uwe considers himself the license maintainer.   The grid can be contained in other software or be offered for download.  Attribution is desired. Format translation is also allowed, if the original precision is maintained.  But in case of changes or additions the name BeTA2007 shall not  be used anymore. The derived product should still make a references to the original.

**Comment by sebastic** [comment]
The license terms as they are now are not acceptable to the Debian FTP Masters, see:

 https://alioth-lists.debian.net/pipermail/pkg-grass-devel/2020-April/084137.html

They have requested a clear license statement that ensures that modifications of the correction values are allowed when using a different name:

 https://alioth-lists.debian.net/pipermail/pkg-grass-devel/2020-April/084168.html

The "if the original precision is maintained" bit is currently considered making it non-free.

**Pull request merged**
