### PR TITLE
Update ellipsoids.rst: typo

### PR DESCRIPTION
**Pull request by mdsumner**
- [x] change typo 'laton' to 'latlon'

todo/questsion: 

- [x]  YES: should lines be fully qualified proj params e.g. '+proj=latlon +R=7000000'
- [x] NO: should family be "lonlat"

### CODE REVIEW

**Comment by kbevers** [comment]
> should lines be fully qualified proj params e.g. '+proj=latlon +R=7000000'

I'd prefer that, yes. The plusses aren't necessary in all cases (e.g. in a gie file or when using the API) but this could easily be confusing when trying things out on he command line where the plusses are mandatory.

> should family be "lonlat"

They are all synonyms so it doesn't really matter. The latitude/longitude order is the ISO standard for representing geographical coordinates though so I have a slight preference for `latlon`.

**Comment by mdsumner** [comment]
great, thanks - updated now

**Review by mwtoews — APPROVED** [review]
Thanks for catching this!

**Comment by mdsumner** [comment]
there is still a dangling +R_V token in the final example, I just wasn't sure how that's meant to work - I was hoping to figure that out and include it here but wasn't able to get to it

**Comment by kbevers** [comment]
Looking at the example it looks alright to me. The `+R_V` flag is used to tell PROJ that you want a sphere of the same volume as the ellipsoid determined by the given parameters (`+a` and `+rf`).

**Pull request merged**
