### PR TITLE
Can remove default parameter.

### PR DESCRIPTION
**Pull request by jidanni**
Shorten string by removing redundancies.

### CODE REVIEW

**Comment by jidanni** [comment]
Anybody have a look at this?

**Comment by hobu** [comment]
> Anybody have a look at this?

I think these are sitting here because no one wants to go through and gather all of your documentation patches into a single PR. If you can do that it will get merged very quickly.

**Comment by jidanni** [comment]
Many years ago I installed git on Linux.


However these years I just use the GitHub web interface.

Any more tinkering by me will be certain disaster.

**Comment by rouault** [comment]
already merged

**Pull request closed without merging**
