### PR TITLE
Fix the constants used for degree/radian conversions.

### PR DESCRIPTION
**Pull request by cffk**
In dmstor.c an inaccurate constant was used for pi/180.  This meant that
90deg converted to radians and back to degrees gave a result which was
larger than 90deg.  The constant has been replaced by DEG_TO_RAD
(defined in proj_api.h).

In rtodms.c, the trailing digits in CONV were wrong; the constant has
been truncated so that all the digits are corrent.

### CODE REVIEW

**Comment by cffk** [comment]
Needless to say that some of the tests have the bad value of pi/180
baked in.  So someone needs to verify the new (presumably more accurate)
values.  I believe that sticking with the old buggy value of pi/180 is
not an option.  It's really bad news that cos(90 deg) is negative and
than 0N 0E and 0N 180E are not on the same meridian.

**Comment by hobu** [comment]
@cffk Please merge/update this when you are comfortable.

**Comment by cffk** [comment]
I recommend slipping this fix to after the release of 4.9.2.  I'll make the merge then to
give people time to address the failing tests.

**Comment by hobu** [comment]
> I recommend slipping this fix to after the release of 4.9.2

Yes, that was my intention. I presume there will be some ripples...

**Comment by cffk** [comment]
I propose to wait a few days before doing a merge, in case anyone wants to
weigh in on the changes I made to the tests...

**Comment by rouault** [comment]
@cffk I think this commit caused the following test failure on MacOSX : https://travis-ci.org/rouault/proj.4/builds/83738157

```
310c310

< -140.100000 -87.000000 987122.418330284 -14429896.539530911 0.000000000

---

> -140.100000 -87.000000    987122.418330284    -14429896.539530909 0.000000000

```

**Comment by cffk** [comment]
OK, I'll fix...

**Pull request merged**
