### PR TITLE
Improved series for the meridian length and its inverse

### LINKED ISSUE #2387: Some suggestions for code cleanup
My recent update to the tmerc documentation #2379 was prompted by queries from NGA (the US National Geospatial Intelligence Agency) figuring what it should do with PROJ.  Along the way there was talk of NGA doing a code review of PROJ.  Of course, we should welcome this.  However, there are many parts of PROJ which are showing their age.  Some of these are ripe for updating to improve:

(a) clarity of the code
(b) accuracy
(c) speed

I've identified the following sections that I'm interested in updating:

1. documentation for Mercator, merc.rst (currently incomplete)
2. implementation of Mercator, merc.cpp (inaccurate, slow, odd parity violated)
3. meridian distance, mlfn.[hc]pp (inaccurate, clumsy inverse)
4. ellipsoid parameters, ell_set.cpp (inaccurate conversions with trig functions)

I realize that this is a somewhat Sisyphean undertaking.  For example, other conformal projections share the defects of the Mercator projection.  However, I figure I'd start chipping away at the parts of PROJ that annoy me the most.  Even if my changes are reckoned to be too piecemeal, it will be good to capture possible code changes for a future more systematic housecleaning.

I will make separate pull requests for these 4 items and these can be discussed in full at that time.  However, holler if you want to know my intentions before I get around to making the changes.

### PR DESCRIPTION
**Pull request by cffk**
This PR addresses #2387   point 3.

Replace the series for the meridian length in the functions
```c++
pj_enfn
pj_mlfn
pj_inv_mlfn
```
in `mlfn.cpp` with improved versions.  The old version of `pj_mlfn` used Snyder's Eq. (3-21) extended from 3rd to 4th order in e^2 and `pj_inv_mlfn` inverted this by an iterative method.

The new version uses 6th order expansions in the third flattening, n, for both `pj_mlfn` and `pj_inv_mlfn`.  Expansions in n have a smaller truncation error that the corresponding expansion in e^2.  Increasing the order to 6th (from 4th) means that the routines give full double precision accuracy for |f| <= 1/150.  Because the meridian length is used in several projections, it's important that it be accurate as possible.  For example, now the azimuthal equidistant projection is equally accurate in the polar (uses `pj_mlfn`) and oblique (uses the geodesic routines) aspects.

The increased accuracy tripped one of the tests: an instance of the projection `+proj=utm +approx`.  The fix is to use the non-approx results for the expected values.

Presumably this change results in `pj_mlfn` being a little slower while `pj_inv_mlfn` is considerably faster (since there's no iteration involved).  Incidentally the new method for `pj_inv_mlfn` uses Snyder's recommended series Eq. (3-23) extended from 4th to 6th order (Snyder writes n as e_1).

More discussion of the series used here is given in my recent paper

> On auxiliary latitudes, https://arxiv.org/abs/2212.05818

 - [x] Partially closes #2387
 - [x] Tests adjusted
 - [x] Added clear title that can be used to generate release notes

### CODE REVIEW

**Comment by rouault** [comment]
Can you try running the new ``bench_proj_trans`` binary before and after your changes ?
I get for example the following with current master:
```
$ bin/bench_proj_trans --pipeline "+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=utm +zone=31 +ellps=GRS80 +approx" 2 49
2 49 -> 426857.98771659 5427937.52334353
Duration: 407 ms
Throughput: 12.29 million coordinates/s

$ bin/bench_proj_trans --pipeline "+proj=pipeline +step +inv +proj=utm +zone=31 +ellps=GRS80 +approx +step +proj=unitconvert +xy_in=rad +xy_out=deg" 426857.98771659 5427937.52334353
426857.98771659 5427937.52334353 -> 1.99999999999991 48.9999999999999
Duration: 714 ms
Throughput: 7.00 million coordinates/s
```

**Comment by cffk** [comment]
Here you go:
```
BEFORE
2 49 -> 426857.98771659 5427937.52334353
Duration: 305 ms
Throughput: 16.39 million coordinates/s
426857.98771659 5427937.52334353 -> 1.99999999999991 48.9999999999999
Duration: 546 ms
Throughput: 9.16 million coordinates/s

AFTER
2 49 -> 426857.98771659 5427937.52334229
Duration: 333 ms
Throughput: 15.02 million coordinates/s
426857.98771659 5427937.52334353 -> 1.99999999999969 49.000000000011
Duration: 496 ms
Throughput: 10.08 million coordinates/s
```

These timings are roughly in line with my expectations.

**Review by rouault — APPROVED** [review]
I've given this a try against GDAL autotest suite whose one test is sensitive to +proj=utm +approx results, and things are good.
It is also very cool to have a non-iterative implementation of inv_mlfn, in the perspective of PROJ having a day vectorized implementations of coordinate transformations, transforming several coordinates at once in SIMD registers.
So +1 from me

**Review by kbevers — APPROVED** [review]
Looks good to me. Great addition!

**Pull request merged**
