### PR TITLE
Major restructure and rewrite of docs.

### PR DESCRIPTION
**Pull request by kbevers**
Improving the documentation in anticipation of the next release. Major restructure and rewrite already, but still a work in progress. This gives a much needed introduction to how to use PROJ.4. Both the with the _cs2cs_ and _transformation pipeline_ way of transforming coordinates. Emphasis is mostly places on the transformation pipeline framework, but the old cs2cs framework is also described. Much of the new text is lifted from the paper @busstoptaktik and I wrote for FIG WW2017. There is no problems with copyrights since Thomas and I have exclusive rights to the contents and are okay with using the text here as well.

I will extend this PR with proper documentation of the new API as well.

This PR is meant to be merged just before the next version of PROJ.4 is released (don't want to release the docs prematurely on proj4.org).

### CODE REVIEW

**Comment by kbevers** [comment]
Since it is quite difficult to grasp the changes of the documentation in diff-format I've put the updated docs on my github-pages: https://kbevers.github.io/

I'll try to keep it in syncs with actual changes I make. Comments and suggestions are appreciated.

**Comment by cffk** [comment]
Some URL housecleaning requests (migrating to https as much as possible)
http://dx.doi.org -> https://doi.org
http://geographiclib.sourceforge.net -> https://geographiclib.sourceforge.io
http://geographiclib.sf.net -> https://geographiclib.sourceforge.io

**Comment by cffk** [comment]
A couple of instances of misformatting on https://kbevers.github.io/geodesic.html
(1) '''87''' should be **87**, (2) there's a bullet list in the section on the triaxial case
where the bullets have ended up as *'s.

**Comment by kbevers** [comment]
@cffk I think in general the "geodesic calculations" needs a overhaul to better fit the rest of the documentation. The current page I think was migrated from the old wiki. I would like to make it fit better with the rest of the docs, but I still haven't decided on exactly how. One option is to move it to the "Using PROJ.4" chapter, split into a theory and usage sections and omitting the parts with mailing list entries and other software. What do you think about that?

Most of the links to the mailing lists are also dead, by the way.

**Comment by cffk** [comment]
This is a fine idea...  The original geodesic page was thrown together when the treatment of geodesics was in flux.  That said, some of the mailing lists conversations are (were!) of interest.  I see that the mailing list is still available at http://lists.maptools.org/mailman/listinfo/proj but the messages aren't keyed in the same way!

**Comment by kbevers** [comment]
> That said, some of the mailing lists conversations are (were!) of interest. 

I am sure they are. Perhaps they can be summed up in the text somehow. Any help with this is appreciated, since I am mostly focusing on documenting the new API for now.

**Comment by kbevers** [comment]
The work continues in https://github.com/OSGeo/proj.4/pull/577

**Pull request closed without merging**
