### PR TITLE
configure.ac: replace '==' by '=' to avoid Bashism (patch by Greg Troxel)

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by kbevers** [comment]
So... Another RC?

**Comment by rouault** [comment]
No, I don't think that's worth it. That's just a warning in Greg's linting tools, and he patched it on his side. But we can backport this to 6.0 branch for the next bugfix release

**Comment by kbevers** [comment]
Okay, great. I think we've had enough RC's for now :) I'll call for a vote for of RC4 promotion to final today then.

**Comment by rouault** [comment]
Merged and cherry-picked to 6.0

**Pull request merged**
