### PR TITLE
update Dockerfile for osgeo/proj-docs to include spell checking

### PR DESCRIPTION
**Pull request by hobu**
Add spell checking capability to Sphinx and catch up to latest.

The `osgeo/proj-docs` docker image has been updated with these additions.

### CODE REVIEW

**Comment by kbevers** [comment]
Cool. How does this work? Sphinx fails if I've spelled something wrong?

**Comment by hobu** [comment]
you get a list of words and line numbers. I added a ``make spell`` target to PDAL which does this and found a ton of things. https://github.com/PDAL/PDAL/pull/3186

I suppose you could make it fail, but that would involve adding a lot of special words to the dictionary.

**Comment by kbevers** [comment]
> I added a make spell target to PDAL which does this and found a ton of things

Do you mind adding that here as well? As far as I can tell this PR only prepares the Docker image for this, right?

> I suppose you could make it fail, but that would involve adding a lot of special words to the dictionary.

Right, that could be a pain in the ass to maintain. `make spell` is great addition in itself, I am sure I have contributed my fair share of spelling errors!

**Comment by hobu** [comment]
> Do you mind adding that here as well?

This should be merged and a new one opened adding spelling support.

**Pull request merged**
