### PR TITLE
GeoTIFF grids: support UNITTYPE=arc-seconds per year for temporal hgridshift

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Review by kbevers — COMMENTED** [review]
This looks like an extensenion to the GTG format. Are we keeping track of version numbers somewhere? And should it be raised?

**Comment by rouault** [comment]
> This looks like an extensenion to the GTG format. Are we keeping track of version numbers somewhere? And should it be raised?

there is no version numbering. I could potentially add a mention this is only supported since PROJ 9.1.1

**Comment by kbevers** [comment]
>  there is no version numbering

Would it make sense to have that? We do it for the PROJJSON spec already. It's been fairly stable so far but I think it would be good to be transparent about the evolution of the format.

**Comment by rouault** [comment]
> Would it make sense to have that?

ok, I've added a Revisions section at the bottom of the .rst

**Comment by kbevers** [comment]
>  ok, I've added a Revisions section at the bottom of the .rst

Thanks. Good to go from my point of view!

**Pull request merged**
