### PR TITLE
normalizeForVisualization(): make it switch axis for EPSG:5482 (RSRGD2000 / RSPS2000)

### LINKED ISSUE #2254: Incorrect Projection Parameters for RSRGD2000 / RSPS2000
#### Example of problem
I think projection EPSG:5482 has an issue with the application of projection parameters in PROJ 7.1.0 (master). 

Using projinfo it seems the first standard parallel parameter is not defining lat true scale parameter for the sterographic projection method. See:

```
$ projinfo EPSG:5482 -o WKT1:GDAL
WKT1:GDAL string:
PROJCS["RSRGD2000 / RSPS2000",
    GEOGCS["RSRGD2000",
        DATUM["Ross_Sea_Region_Geodetic_Datum_2000",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            AUTHORITY["EPSG","6764"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4764"]],
    PROJECTION["Polar_Stereographic"],
    PARAMETER["latitude_of_origin",-90],
    PARAMETER["central_meridian",180],
    PARAMETER["scale_factor",0.994],
    PARAMETER["false_easting",5000000],
    PARAMETER["false_northing",1000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","5482"]]
```

I would expect to see PARAMETER["standard_parallel_1",-90] in the WKT definition, so PROJ includes the +lat_ts=-90 proj parameter (rather than the default of +lat_ts=0) .

```
projinfo 'PROJCS["RSRGD2000_RSPS2000", GEOGCS["GCS_RSRGD2000", DATUM["D_Ross_Sea_Region_Geodetic_Datum_2000", SPHEROID["GRS_1980",6378137,298.257222101]], PRIMEM["Greenwich",0], UNIT["Degree",0.017453292519943295]], PROJECTION["Stereographic_South_Pole"], PARAMETER["standard_parallel_1",-90], PARAMETER["central_meridian",180], PARAMETER["false_easting",5000000], PARAMETER["false_northing",1000000], UNIT["Meter",1]]' -o PROJ
PROJ.4 string:
+proj=stere +lat_0=-90 +lat_ts=-90 +lon_0=180 +x_0=5000000 +y_0=1000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs
```

I checked with GDAL 2.4.2/PROJ 5.2.0 and it does output the correct PROJ projection parameters, even though the WKT is the same. So it looks like some change in the conversion and mapping of projection parameters between PROJ versions 5.2.0 and 7.10-master...

```
>>> import gdal
>>> gdal.VersionInfo()
'2040200'
>>> import osr
>>> proj = osr.SpatialReference()
>>> proj.ImportFromEPSG(5482)
0
>>> proj.ExportToPrettyWkt()
'PROJCS["RSRGD2000 / RSPS2000",\n    GEOGCS["RSRGD2000",\n        DATUM["Ross_Sea_Region_Geodetic_Datum_2000",\n            SPHEROID["GRS 1980",6378137,298.257222101,\n                AUTHORITY["EPSG","7019"]],\n            TOWGS84[0,0,0,0,0,0,0],\n            AUTHORITY["EPSG","6764"]],\n        PRIMEM["Greenwich",0,\n            AUTHORITY["EPSG","8901"]],\n        UNIT["degree",0.0174532925199433,\n            AUTHORITY["EPSG","9122"]],\n        AUTHORITY["EPSG","4764"]],\n    PROJECTION["Polar_Stereographic"],\n    PARAMETER["latitude_of_origin",-90],\n    PARAMETER["central_meridian",180],\n    PARAMETER["scale_factor",0.994],\n    PARAMETER["false_easting",5000000],\n    PARAMETER["false_northing",1000000],\n    UNIT["metre",1,\n        AUTHORITY["EPSG","9001"]],\n    AUTHORITY["EPSG","5482"]]'
>>> proj.ExportToProj4()
'+proj=stere +lat_0=-90 +lat_ts=-90 +lon_0=180 +k=0.994 +x_0=5000000 +y_0=1000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs '
```

#### Environment Information
 - PROJ master/5.2.0
 - MacOS/Windows

#### Installation method
 - from source, shipped with QGIS MacOS

### PR DESCRIPTION
**Pull request by rouault**
Fixes #2254

### CODE REVIEW

**Comment by palmerj** [comment]
Can you please be backport this to 6.3? I see QGIS is currently built against 6.3.X

**Comment by rouault** [comment]
There is no more 6.3 maintenance release planned. The next one will be 7.1 this July 1st
QGIS Windows builds should normally switch soon to PROJ 7.0 (and ultimately catch up with 7.1)

**Comment by palmerj** [comment]
Ok thanks. So in the mean time what's the workaround? Add a custom RSPS2000 projection  to QGIS with:

```
+proj=pipeline
+step +proj=axisswap +order=2,1 
+step +proj=unitconvert +xy_in=deg +xy_out=rad
+step +proj=stere +lat_0=-90 +lon_0=180 +k=0.994 
+x_0=5000000 +y_0=1000000 +ellps=GRS80
+step +proj=axisswap +order=2,1 
```

?

**Comment by rouault** [comment]
Pipelines will not be accepted, as they model a transformation, ot a CRS. I've tried just the PROJ CRS string "+proj=stere +lat_0=-90 +lon_0=180 +k=0.994 +x_0=5000000 +y_0=1000000 +ellps=GRS80" and it is valid, but it is then refused as being equivalent to EPSG:5482. 
Trying with an amended WKT2 with the "gis friendly order" also leads to the same error. QGIS is too smart... The workaround would probably then to remove EPSG:5482 definition from at least QGIS srs.db, and potentially from proj.db too, but I didn't try that

**Comment by palmerj** [comment]
Note I tried deleting from srs.db and proj.db and then entering the above proj string as a custom projection. Now the data won't show at all. 

But I got it working by updating the srs.db parameters. 

```
sqlite3 /path/to/qgis/share/srs.db "UPDATE tbl_srs SET parameters = '+proj=stere +lat_0=-90 +lon_0=180 +k=0.994 +x_0=5000000 +y_0=1000000 +ellps=GRS80' WHERE srid = 5482;"
```

The existing parameters where:
```
'+proj=stere +lat_0=-90 +lat_ts=-90 +lon_0=180 +k=0.994 +x_0=5000000 +y_0=1000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs'
```

I'm still a little confused how this is working as not axis parameters have been changed!

**Pull request merged**
