### PR TITLE
Implementation of Web Mercator projection

### PR DESCRIPTION
**Pull request by dtutic**
New webmerc (Web Mercator) projection is implemented as projection of a sphere. Consequences are that projection factors are calculated for Mercator projection of a sphere (i.e. no angular distortion) e.g.:

```
./proj +proj=webmerc +ellps=WGS84 -V
#Web Mercator / Pseudo Mercator
#	Cyl, Sph
#	
# +proj=webmerc +ellps=WGS84
#Final Earth figure: sphere
#  Radius: 6378137.000
0 0
Longitude: 0dE [ 0 ]
Latitude:  0dN [ 0 ]
Easting (x):   0.00
Northing (y):  0.00
Meridian scale (h) : 1.00000000  ( 2.319e-09 % error )
Parallel scale (k) : 1.00000000  ( 0 % error )
Areal scale (s):     1.00000000  ( 2.319e-09 % error )
Angular distortion (w): 0.000
Meridian/Parallel angle: 90.00000
Convergence : 0d [ -0.00000000 ]
Max-min (Tissot axis a-b) scale error: 1.00000 1.00000
```
These are not properties of Web Mercator projection which is non-conformal projection. It should be implemented for ellipsoid, e.g.

```
PJ *PROJECTION(webmerc) {

    P->inv = webe_inverse;
    P->fwd = webe_forward;
    return P;
}

static XY webe_forward (LP lp, PJ *P) {          /* Web Mercator Ellipsoidal, forward */
    XY xy = {0.0,0.0};
    if (fabs(fabs(lp.phi) - M_HALFPI) <= EPS10) {
        proj_errno_set(P, PJD_ERR_TOLERANCE_CONDITION);
        return xy;
    }
    xy.x = lp.lam;
    xy.y = logtanpfpim1(lp.phi);
    return xy;
}

static LP webe_inverse (XY xy, PJ *P) {          /* Web Mercator Ellipsoidal, inverse */
    LP lp = {0.0,0.0};
    if ((lp.phi = M_HALFPI - 2. * atan(exp(-xy.y / P->k0))) == HUGE_VAL) {
        proj_errno_set(P, PJD_ERR_TOLERANCE_CONDITION);
        return lp;
}
    lp.lam = xy.x;
    return lp;
}
```
which gives proper projection factors and final Earth figure, e.g.

```
./proj +proj=webmerc +ellps=WGS84 -V
#Web Mercator / Pseudo Mercator
#	Cyl, Sph
#	
# +proj=webmerc +ellps=WGS84
#Final Earth figure: ellipsoid
#  Major axis (a): 6378137.000
#  1/flattening: 298.257224
#  squared eccentricity: 0.006694379990
0 0
Longitude: 0dE [ 0 ]
Latitude:  0dN [ 0 ]
Easting (x):   0.00
Northing (y):  0.00
Meridian scale (h) : 1.00673950  ( 0.6739 % error )
Parallel scale (k) : 1.00000000  ( 0 % error )
Areal scale (s):     1.00673950  ( 0.6739 % error )
Angular distortion (w): 0.385
Meridian/Parallel angle: 90.00000
Convergence : 0d [ -0.00000000 ]
Max-min (Tissot axis a-b) scale error: 1.00674 1.00000
```
Also line

`PROJ_HEAD(webmerc, "Web Mercator / Pseudo Mercator") "\n\tCyl, Sph\n\t";
`

should be

`PROJ_HEAD(webmerc, "Web Mercator / Pseudo Mercator") "\n\tCyl, Ell\n\t";
`

because there is no (at least I am not aware of) definition of Web Mercator projection for sphere, so sphere should be avoided when we speak of Web Mercator projection. It is projection of rotational ellipsoid defined with specific equations which are chosen to be same as equations for Mercator of sphere, but it is different projection with different properties (cylindrical non-conformal, non-equareal, non-equidistant).

Avoiding introduction of sphere when talking and defining Web Mercator projection will remove confusion that user uses ellipsoid as reference surface but projection is for sphere (which, in fact, is not)!

### CODE REVIEW

**Comment by kbevers** [comment]
Why did you close it again? I need to check this a bit closer but at a first glance this looks alright to me.

**Comment by kbevers** [comment]
Yeah, I saw that. I guess that means you want someone else to do the implementation?

**Comment by dtutic** [comment]
I can do it, but I need some time to learn how to do it properly on Github. I am not regular Github user, and have never took time to learn it properly. Maybe now it is chance to do it.

---- Kristian Evers wrote ----


Yeah, I saw that. I guess that means you want someone else to do the implementation?

**Comment by kbevers** [comment]
> I can do it, but I need some time to learn how to do it properly on Github. I am not regular Github user, and have never took time to learn it properly. Maybe now it is chance to do it

I'd say that's as good a time as any to learn it :-) Let me know if you need help with something.

**Pull request closed without merging**
