### PR TITLE
Database: rework a bit consistency checks triggers

### PR DESCRIPTION
**Pull request by rouault**
- Move insertion triggers implementing consistency checks in a dedicated file.
  Can make it easier to disable them to speed the proj.db speed process during some development scenarios.
- move final consistency checks on transformations as insert time triggers
- consistency_checks_triggers.sql: add consistency check for 1st step of a concatenated operation
- consistency_checks_triggers.sql: checks for Geog3D to Geog2D+GravityRelatedHeight/Depth family of methods

### CODE REVIEW

**Comment by rouault** [comment]
Rebased on top of latest master with the EPSG v11.006 updates who fix some inconsistencies

**Comment by rouault** [comment]
Rebased on top of latest master with the EPSG v11.007 updates

**Comment by rouault** [comment]
Rebased on top of lastest master to take into account https://github.com/OSGeo/PROJ/pull/4098 ("Make NKG Transformation names unique")

**Comment by rouault** [comment]
@kbevers the consistency checks detected 2 remaining occurences of duplicated NKG transformation names, which I propose to resolve with a8db330c09734d248726c15d421af21825ade1af

**Comment by kbevers** [comment]
Ah yes, I should have spotted those as well. Your suggestion is good.

**Pull request merged**
