### PR TITLE
Database: update to EPSG 9.8.2

### PR DESCRIPTION
**Pull request by rouault**
With limitation of https://github.com/OSGeo/PROJ/issues/1632 regarding
concatenated operations with more than 3 steps.

### CODE REVIEW

**Comment by kbevers** [comment]
@rouault do you want to merge this now? Or do you want to take care of #1632 first?

**Comment by rouault** [comment]
> do you want to merge this now?

yes

>  do you want to take care of #1632 first?

I don't have immediate plans about addressing #1632, hence its creation.

**Comment by kbevers** [comment]
Let's get it merged then. Also, not adding support for the extra steps means that this can be included in 6.2.1 which is probably a good thing.

**Comment by kbevers** [comment]
> ... included in 6.2.1 which is probably a good thing

> The backport to 6.2 failed:

maybe not... I'll take a look at manually backporting this later. Unless @rouault can say right away that it is a waste of time?

**Pull request merged**
