### PR TITLE
Database: update to EPSG v11.005

### PR DESCRIPTION
**Pull request by jjimenezshaw**

### CODE REVIEW

**Comment by jjimenezshaw** [comment]
I see now https://github.com/OSGeo/PROJ/pull/4071
I don't know in which order should we merge (or even wait for a later epsg release). At least in this PR there are many test fixed due to the new added WGS84 datum (G2296)

In this version the new transformation
https://epsg.org/transformation_10568/ETRS89-to-ETRS89-Baltic-1957-height-1.html
uses the same name as
https://epsg.org/transformation_8361/ETRS89-to-ETRS89-Baltic-1957-height-1.html
We expect a soon new update fixing it.

**Comment by rouault** [comment]
> I don't know in which order should we merge (or even wait for a later epsg release)

I've just added commit 243144eb17ae6fce3563a9205f9b640dc847f474 in PR #4071, so we should be good merging in any order

**Comment by rouault** [comment]
I would be tempted to wait for the next EPSG update to remove the duplication, or if we are eager to use that one, add a tweak in the import script to rename the new Czech transformation to what is going to be most certainly its fixed name, that is "ETRS89 to ETRS89 + Baltic 1957 height (2)"

**Comment by rouault** [comment]
v11.006 is available at https://epsg.org/download-dataset.html

**Comment by jjimenezshaw** [comment]
> v11.006 is available at https://epsg.org/download-dataset.html

Thanks @rouault 
I get an error: 
```python3 ./build_db.py 
Skipping coordinate system ('Bin grid I=J+90 CS (datatype=real). Axes: I,J.', 1051, 'affine', 2)
Skipping coordinate system ('Bin grid I=J-90 CS (datatype=real). Axes: I,J.', 1052, 'affine', 2)
Traceback (most recent call last):
  File "/home/jshaw/jjimenezshaw/PROJ/scripts/./build_db.py", line 1250, in <module>
    fill_grid_transformation(proj_db_cursor)
  File "/home/jshaw/jjimenezshaw/PROJ/scripts/./build_db.py", line 798, in fill_grid_transformation
    assert n_params == 1, (code, name, method_code)
AssertionError: (10560, 'ETRS89 to ETRS89 + DKLAT(2022) depth (1)', 1128)
```

What is the idea here? Add exceptions to those cases and move forward?

**Comment by rouault** [comment]
> What is the idea here? Add exceptions to those cases and move forward?

yes, likely. Note the comment in the script about updating src/iso19111/operation/singleoperation.cpp

**Comment by jjimenezshaw** [comment]
I added transformation methods 1128 and 1129 to the list of "2 params".

There is something strange. In https://github.com/OSGeo/PROJ/pull/4071/files it creates the file `data/sql/builtin_authorities.sql`, but it is not in the repository. Should it be in the repo? (I can add it now)

**Comment by rouault** [comment]
> it creates the file `data/sql/builtin_authorities.sql`

ah build_db.py probably creates it? I'd suggest modifying it as such:
```
diff --git a/scripts/build_db.py b/scripts/build_db.py
index 456c4accf..4797d64bd 100755
--- a/scripts/build_db.py
+++ b/scripts/build_db.py
@@ -1085,6 +1085,7 @@ proj_db_cursor.execute("INSERT INTO celestial_body VALUES('PROJ', 'EARTH', 'Eart
 
 proj_db_cursor.execute("""DROP VIEW conversion;""")
 proj_db_cursor.execute("""DROP TABLE conversion_table;""")
+proj_db_cursor.execute("""DROP TABLE builtin_authorities;""")
 proj_db_cursor.execute("""CREATE TABLE conversion(
     auth_name TEXT NOT NULL CHECK (length(auth_name) >= 1),
     code TEXT NOT NULL CHECK (length(code) >= 1),
```

**Comment by jjimenezshaw** [comment]
Included in https://github.com/OSGeo/PROJ/pull/4085

**Comment by rouault** [comment]
closing as superseded per #4085

**Pull request closed without merging**
