### PR TITLE
Adding a new peer-reviewed authority

### PR DESCRIPTION
**Pull request by rouault**
Published in https://talks.osgeo.org/media/foss4g-europe-2024/submissions/B8CETX/resources/WGS_84_I_dont_know_I_dont_care_pTbpl9n.pdf, slides 37-38

Demo:
```
$ PROJ_DATA=data bin/projinfo IDNK:UTM_31N+IDNK:VERTICAL
PROJ.4 string:
+proj=utm +zone=31 +ellps=GRS80 +units=m +vunits=m +no_defs +type=crs

WKT2:2019 string:
COMPOUNDCRS["Unknown / UTM zone 31N + Unknown vertical CRS",
    PROJCRS["Unknown / UTM zone 31N",
        BASEGEOGCRS["Unknown geographic 2D CRS",
            DATUM["Unknown geodetic datum",
                ELLIPSOID["GRS 1980",6378137,298.257222101,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            ID["IDNK","GEOGRAPHIC"]],
        CONVERSION["UTM zone 31N",
            METHOD["Transverse Mercator",
                ID["EPSG",9807]],
            PARAMETER["Latitude of natural origin",0,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8801]],
            PARAMETER["Longitude of natural origin",3,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8802]],
            PARAMETER["Scale factor at natural origin",0.9996,
                SCALEUNIT["unity",1],
                ID["EPSG",8805]],
            PARAMETER["False easting",500000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8806]],
            PARAMETER["False northing",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8807]]],
        CS[Cartesian,2],
            AXIS["(E)",east,
                ORDER[1],
                LENGTHUNIT["metre",1]],
            AXIS["(N)",north,
                ORDER[2],
                LENGTHUNIT["metre",1]],
        ID["IDNK","UTM_31N"]],
    VERTCRS["Unknown vertical CRS",
        VDATUM["Unknown vertical datum"],
        CS[vertical,1],
            AXIS["gravity-related height (H)",up,
                LENGTHUNIT["metre",1]],
        ID["IDNK","VERTICAL"]]]
```

### CODE REVIEW

**Comment by hobu** [comment]
> peer-reviewed authority

I appreciate the fun easter egg, but it does bring up the topic of PROJ maintaining authorities. I thought project policy was to be not to do so given we have no way to upstream them to regularized standards bodies in a way that doesn't break their definition(s). 

I understand the joke coming from @jjimenezshaw's talk, but I admit I'm a bit concerned that PROJ would be adding authorities. I see the PR is hiding it by masking it in the SQL queries, but TBH, I don't know if that's actually better. I'm not 👎 against the PR, but I think we as a project should state our stance on maintaining alternative definition authorities.

**Comment by rouault** [comment]
no problem if we don't end up merging this. This was done with an easter egg mood indeed

**Comment by kbevers** [comment]
I share Howards sentiment. Although it is a fun easter egg it also adds unnecessary complexity to the code, so ultimately I am -1 on this PR.

**Comment by jjimenezshaw** [comment]
I had no time yet to review the code (still in Estonia) 
One option would be to use the PROJ authority, which is already hidden, right?

**Comment by rouault** [comment]
No the PROJ authority is not hidden

**Comment by rouault** [comment]
ok, let's close this

**Pull request closed without merging**
