### PR TITLE
vgridshift: add a +multiplier={value}

### PR DESCRIPTION
**Pull request by rouault**
As mentionned in #1071, it is often unclear how the offset of a vertical grid
is applied.

### CODE REVIEW

**Comment by rouault** [comment]
Another possibility would be to add a +multiplier parameter, and then people would be able to control both direction and multiplier value (in case of non-meter units)

**Comment by kbevers** [comment]
I think the `operation` parameter is too easily confused with a "coordinate operation". Especially when used in gie files: `operation proj = vgridshift grids = ... operation = add`. I'm leaning towards the `+multiplier` parameter. It would also fix your original mm problem.

**Comment by rouault** [comment]
> I'm leaning towards the +multiplier parameter.

Done

**Comment by kbevers** [comment]
Looks good to me. We should reconsider if it makes sense to add the vertcon grids with adjusted units to proj-datumgrids.

**Pull request merged**
