### PR TITLE
Use autoconf for PTHREAD_MUTEX_RECURSIVE (#302)

### PR DESCRIPTION
**Pull request by turepalsson**
On FreeBSD 10, PTHREAD_MUTEX_RECURSIVE exists, but as an enum constant,
not a #define macro, so it cannot be detected using #ifdef.

### CODE REVIEW

**Comment by turepalsson** [comment]
Oh, bother, it breaks on Windows. No idea how to fix that, unfortunately. :)

**Comment by rouault** [comment]
Perhaps including proj_config.h only within a #ifndef _MSC_VER #endif

**Comment by turepalsson** [comment]
Ah, I was worrying that I didn't know what PTHREAD_\* stuff to use on Windows, but now I realize that Windows doesn't use pthreads at all.  :)

How about moving the include inside the existing #ifndef _WIN32, would that make sense?

**Comment by rouault** [comment]
> How about moving the include inside the existing #ifndef _WIN32, would that make sense?

Should be fined too

**Comment by hobu** [comment]
To be included in 4.9.2RC2...

**Comment by rouault** [comment]
Merged in master

**Pull request closed without merging**
