### PR TITLE
Doc updates, most notably rewrite of FAQ

### PR DESCRIPTION
**Pull request by kbevers**
Some minor doc updates and a work-in-progress rewrite of the FAQ.

Suggestions for more frequently asked questions are welcome. The once I have added so far are mostly in response to questions I often get asked in my job at the Danish geodetic office. I have removed basically all the existing questions as they were from a time where there wasn't much other documentation. Most of them were covered better in other places or was simply not applicable any more. At least in my opinion, if I have removed something you think is important please let me know.

### CODE REVIEW

**Comment by snowman2** [comment]
I think I remember something about `+init` style epsg projection support being deprecated. If this is true, documentation about that would be helpful.

**Comment by snowman2** [comment]
It would also be useful to have this documented: https://github.com/pyproj4/pyproj/issues/201

**Comment by kbevers** [comment]
Good suggestions. I will try to include those later today.

**Comment by snowman2** [comment]
Perfect, thanks!

**Pull request merged**
