### PR TITLE
Man Page Updates

### PR DESCRIPTION
**Pull request by micahcochran**
cs2cs header was updated.  HOME PAGE links were changed.  Converted man pages to html using man2html program using option "-r".  Any changes in the html are changes that already existed in the original man page format.

This is in regard to issue #337 .
[ci skip]

### CODE REVIEW

**Comment by micahcochran** [comment]
Thanks!

**Comment by cffk** [comment]
For the record, #355 updated geod.1 but not the html version.  Should I do this?
In an ideal world the html file would not be checked into git, but would be created
when a release is packaged (as is the ./configure script, for example).

**Comment by hobu** [comment]
I'm trying to get a process together to generate stuff from Sphinx too, but i'm not quite there yet

http://proj4.org

**Comment by micahcochran** [comment]
When I was updating this, I was thinking it would be nice to have a shell script that generated the html.  I think there needs to be an overhaul of this.

I was simply running:

```
man2html -r man/man1/geod.1 > html/man_geod.html
```

I tried to regenerate pj_init.3 and man2html choked on the input, but man is fine with pj_init.3.  I did figure out how to use groff to do this, but I didn't like groff's output.

I should be able to get a shell script that creates an html version of the man pages.  It won't be compatible with Windows, but it might be an improvement.

**Comment by cffk** [comment]
Assuming this is done at the packaging stage, there's no need for compatibility with windows.
(Presumably autogen is being run on a Unix-like system.)

**Pull request merged**
