### PR TITLE
Fix case of proj-datumgrid filename.

### PR DESCRIPTION
**Pull request by sebastic**
The files use lowercase.

### CODE REVIEW

**Comment by kbevers** [comment]
Actually I prefer the uppercase "PROJ" after the lengthy discussions about names. But I haven't been consistent in that regard myself with the release candidates so it is probably better to stick with the lowercase "proj". In line 92 PROJ-x.y.z.tar.gz should also be changed to lowercase.

**Comment by sebastic** [comment]
The filenames of the release tarballs should not be changed.

**Comment by kbevers** [comment]
> The filenames of the release tarballs should not be changed.

Out of curriosity, is it common practice to always have source tarballs in lowercase letters only?

**Comment by sebastic** [comment]
> Out of curriosity, is it common practice to always have source tarballs in lowercase letters only?

Yes, uppercase or mixed case release tarballs are quite uncommon (in the Linux world).

**Comment by kbevers** [comment]
Alright, no need to break that tradition. Thanks for pointing it out.

**Pull request merged**
