### PR TITLE
Add vertical grid files for PL-geoid-2011, Polish geoid model

### PR DESCRIPTION
**Pull request by AlexBass05**
Update metadata.sql to PROJ-data version 1.9

Corresponding PR for PROJ-data: https://github.com/OSGeo/PROJ-data/pull/74

### CODE REVIEW

**Comment by rouault** [comment]
@kbevers What is our policy regarding backport of new database entries and grids ? Is a proj-data 1.9 OK for 8.2.1, or is it for 9.0 only ?

**Comment by rouault** [comment]
@kbevers Gentle ping w.r.t above question

**Comment by kbevers** [comment]
Sorry @rouault, I missed it the first time.

I think we've pushed a new proj-data release for a patch release of PROJ once because the content of the EPSG database changed and required an updated grid. I prefer to only push proj-data release alongside PROJ minor and major release. But there are not set rules so if there's a good reason for a backport and a new proj-data release for 8.2.1 it is possible.

**Comment by rouault** [comment]
let's push that to 9.0 only then

**Pull request merged**
