### PR TITLE
JSON/WKT: avoid precision issues on non-Intel architectures on coordinate epochs (fixes #3632)

### LINKED ISSUE #3632: 9.2.0-rc1 fails to build on non-amd64 architectures due to test failures
The Debian package build for PROJ 9.2.0-rc1 failed on several architectures, see:

 https://buildd.debian.org/status/package.php?p=proj&suite=experimental

The following tests fail due to rounding issues:

 * json_import.geodetic_reference_frame_with_anchor_epoch
 * json_import.vertical_reference_frame_with_anchor_epoch

```
54: ./test/unit/test_io.cpp:13180: Failure
54: Expected equality of these values:
54:   grf->exportToJSON(&(JSONFormatter::create()->setSchema("foo")))
54:     Which is: "{\n  \"$schema\": \"foo\",\n  \"type\": \"GeodeticReferenceFrame\",\n  \"name\": \"my_name\",\n  \"anchor_epoch\": 2002.499999999999,\n  \"ellipsoid\": {\n    \"name\": \"WGS 84\",\n    \"semi_major_axis\": 6378137,\n    \"inverse_flattening\": 298.257223563\n  }\n}"
54:   json
54:     Which is: "{\n  \"$schema\": \"foo\",\n  \"type\": \"GeodeticReferenceFrame\",\n  \"name\": \"my_name\",\n  \"anchor_epoch\": 2002.5,\n  \"ellipsoid\": {\n    \"name\": \"WGS 84\",\n    \"semi_major_axis\": 6378137,\n    \"inverse_flattening\": 298.257223563\n  }\n}"
54: With diff:
54: @@ -3,5 +3,5 @@
54:    \"type\": \"GeodeticReferenceFrame\",
54:    \"name\": \"my_name\",
54: -  \"anchor_epoch\": 2002.499999999999,
54: +  \"anchor_epoch\": 2002.5,
54:    \"ellipsoid\": {
54:      \"name\": \"WGS 84\",
54: 
54: [  FAILED  ] json_import.geodetic_reference_frame_with_anchor_epoch (0 ms)
[...]
54: ./test/unit/test_io.cpp:15550: Failure
54: Expected equality of these values:
54:   vrf->exportToJSON(&(JSONFormatter::create()->setSchema("foo")))
54:     Which is: "{\n  \"$schema\": \"foo\",\n  \"type\": \"VerticalReferenceFrame\",\n  \"name\": \"my_name\",\n  \"anchor\": \"my_anchor_definition\",\n  \"anchor_epoch\": 2002.499999999999\n}"
54:   json
54:     Which is: "{\n  \"$schema\": \"foo\",\n  \"type\": \"VerticalReferenceFrame\",\n  \"name\": \"my_name\",\n  \"anchor\": \"my_anchor_definition\",\n  \"anchor_epoch\": 2002.5\n}"
54: With diff:
54: @@ -4,4 +4,4 @@
54:    \"name\": \"my_name\",
54:    \"anchor\": \"my_anchor_definition\",
54: -  \"anchor_epoch\": 2002.499999999999
54: +  \"anchor_epoch\": 2002.5
54:  }
54: 
54: [  FAILED  ] json_import.vertical_reference_frame_with_anchor_epoch (1 ms)
[...]
./test/unit/test_io.cpp:13180: Failure
Expected equality of these values:
  grf->exportToJSON(&(JSONFormatter::create()->setSchema("foo")))
    Which is: "{\n  \"$schema\": \"foo\",\n  \"type\": \"GeodeticReferenceFrame\",\n  \"name\": \"my_name\",\n  \"anchor_epoch\": 2002.499999999999,\n  \"ellipsoid\": {\n    \"name\": \"WGS 84\",\n    \"semi_major_axis\": 6378137,\n    \"inverse_flattening\": 298.257223563\n  }\n}"
  json
    Which is: "{\n  \"$schema\": \"foo\",\n  \"type\": \"GeodeticReferenceFrame\",\n  \"name\": \"my_name\",\n  \"anchor_epoch\": 2002.5,\n  \"ellipsoid\": {\n    \"name\": \"WGS 84\",\n    \"semi_major_axis\": 6378137,\n    \"inverse_flattening\": 298.257223563\n  }\n}"
With diff:
@@ -3,5 +3,5 @@
   \"type\": \"GeodeticReferenceFrame\",
   \"name\": \"my_name\",
-  \"anchor_epoch\": 2002.499999999999,
+  \"anchor_epoch\": 2002.5,
   \"ellipsoid\": {
     \"name\": \"WGS 84\",

[  FAILED  ] json_import.geodetic_reference_frame_with_anchor_epoch (0 ms)
[...]
./test/unit/test_io.cpp:15550: Failure
Expected equality of these values:
  vrf->exportToJSON(&(JSONFormatter::create()->setSchema("foo")))
    Which is: "{\n  \"$schema\": \"foo\",\n  \"type\": \"VerticalReferenceFrame\",\n  \"name\": \"my_name\",\n  \"anchor\": \"my_anchor_definition\",\n  \"anchor_epoch\": 2002.499999999999\n}"
  json
    Which is: "{\n  \"$schema\": \"foo\",\n  \"type\": \"VerticalReferenceFrame\",\n  \"name\": \"my_name\",\n  \"anchor\": \"my_anchor_definition\",\n  \"anchor_epoch\": 2002.5\n}"
With diff:
@@ -4,4 +4,4 @@
   \"name\": \"my_name\",
   \"anchor\": \"my_anchor_definition\",
-  \"anchor_epoch\": 2002.499999999999
+  \"anchor_epoch\": 2002.5
 }

[  FAILED  ] json_import.vertical_reference_frame_with_anchor_epoch (1 ms)
[...]
```
Buildlogs: [armel](https://buildd.debian.org/status/fetch.php?pkg=proj&arch=armel&ver=9.2.0~rc1-1~exp1&stamp=1677083512&file=log), [armhf](https://buildd.debian.org/status/fetch.php?pkg=proj&arch=armhf&ver=9.2.0%7Erc1-1%7Eexp1&stamp=1677083780&raw=0), [mipsel](https://buildd.debian.org/status/fetch.php?pkg=proj&arch=mipsel&ver=9.2.0%7Erc1-1%7Eexp1&stamp=1677083571&raw=0)

### PR DESCRIPTION
**Pull request by rouault**
@sebastic does it help?

### CODE REVIEW

**Comment by sebastic** [comment]
Thanks for the quick action.

Unfortunately the tests still fail the same way with the changes from this PR, see:

 https://buildd.debian.org/status/package.php?p=proj&suite=experimental

**Comment by rouault** [comment]
> Unfortunately the tests still fail the same way with the changes from this PR, see:

hum, weird. Oh well I've added 7b0af478 that should hopefully avoid the issue...

**Comment by sebastic** [comment]
Build now succeeded on armel, armhf, and mipsel, but still failed on [mips64el](https://buildd.debian.org/status/fetch.php?pkg=proj&arch=mips64el&ver=9.2.0%7Erc1-1%7Eexp3&stamp=1677103717&raw=0):
```
55: ./test/unit/gie_self_tests.cpp:1238: Failure
55: The difference between output_over_normalized.xyz.x and -24490287.974520184 is nan, which exceeds 1e-8, where
55: output_over_normalized.xyz.x evaluates to nan,
55: -24490287.974520184 evaluates to -24490287.974520184, and
55: 1e-8 evaluates to 1e-08.
55: [  FAILED  ] gie.proj_create_crs_to_crs_from_pj_force_over (557 ms)
```

**Comment by rouault** [comment]
@sebastic Perhaps fa8f46ce will help for the mips64el failure ?

**Comment by sebastic** [comment]
Thanks, the build now also succeeded on mips64el:

 https://buildd.debian.org/status/package.php?p=proj&suite=experimental

**Pull request merged**
