### PR TITLE
[Backport master] Update utm.rst to show how TM and UTM are related

### PR DESCRIPTION
**Pull request by rouault**
Backport #4209
 **Authored by:** @jidanni

### CODE REVIEW

**Comment by jidanni** [comment]
Can we keep these on the screen please,

Screenshot 2024-07-28 12 16 41

with no horizontal scrolling.

**Comment by mwtoews** [comment]
Yeah, agree this is an annoyance. The resolutions are to manually wrap the code to around <= 90 chars. Or modify the sphinx template. Probably the first solution to wrap long lines, e.g.:
```bash
$ echo 121 24 | proj +proj=utm +lon_0=123 | proj -I +proj=tmerc \
> +lon_0=123 +x_0=500000 +k=0.9996
121dE	24dN
```
this probably happens in a few places, so it would make sense to collect the pages this happens to put into one PR.

**Comment by jidanni** [comment]
All I know is my version got made into one line by somebody :-(

**Comment by kbevers** [comment]
> All I know is my version got made into one line by somebody :-(

I did that because your original submission didn't include the proper line break and hence wasn't functional.

**Comment by mwtoews** [comment]
For reference, the correct markup for the example is:
```rst
.. code-block:: console

    $ echo 121 24 | proj +proj=utm +lon_0=123 | proj -I +proj=tmerc \
    > +lon_0=123 +x_0=500000 +k=0.9996
    121dE 24dN
```
e.g. here it is with the commands selected to copy&paste, which correctly skips over `$` and `>`:
Screenshot from 2024-07-30 09-00-22


I can take a look at refactoring the docs to make these code blocks more consistent.

**Comment by jidanni** [comment]
Thanks.
I see.
Next time I should use "pipe space backslash newline" instead of just "pipe newline":
- Allows working in makefiles.
- Allows working in non-Linux systems that I'm unfamiliar with.
- Still works in Linux systems.

(The space is just to make it look more graceful.)

**Pull request merged**
