### PR TITLE
Fileapi fgets b110119937

### PR DESCRIPTION
**Pull request by schwehr**
Do not scan past the end of the read data in pj_ctx_fgets
    
use-of-uninitialized-value third_party/proj4/proj/src/pj_fileapi.c:pj_ctx_fgets
    
Found with autofuzz msan

### CODE REVIEW

**Comment by kbevers** [comment]
Looks good to me. Do you mind squashing the last two commits to one before I merge? We should try to have as few commits in the history that breaks the build.

**Comment by mloskot** [comment]
👍 squash squash :)

**Comment by schwehr** [comment]
Will do on the squashing... now to find a block of time longer than 2 minutes

**Comment by schwehr** [comment]
3 became 2

**Comment by mloskot** [comment]
(off topic)
@schwehr Before kids, 30 min free slot wasn't worth booting my laptop. With kids, 10-15 min breaks can make wonders - https://github.com/mloskot/qt-creator-plugin-boostbuild/blob/master/README.md#why-boostbuild-plugin-for-qt-creator

kid napping, laptop warming laps while sat next to cot bed :)

**Pull request merged**
