### PR TITLE
PROJJSON: bump to 0.6 with an additional optional source_crs property…

### PR DESCRIPTION
**Pull request by rouault**
… in abridged_transformation (refs #3428)

### CODE REVIEW

**Comment by rouault** [comment]
@kbevers does that look reasonable to you ? This is an extension of the BoundCRS of WKT adding an explicit sourceCRS to the transformation embedded in the BoundCRS (as it is sometimes a bit fuzzy to know exactly to which CRS the transformation applies too when the sourceCRS of the BoundCRS is something more complex than a regular geographicCRS), but specific to PROJJSON as I don't want to mess with WKT

**Comment by kbevers** [comment]
I'm not sure about this. Is this the first time PROJJSON conceptually diverges from WKT?

**Comment by rouault** [comment]
> I'm not sure about this. Is this the first time PROJJSON conceptually diverges from WKT?

no, we allow BOUNDCRS[] to be used as one of the horizontal or vertical component of a CompoundCRS for example, and we actually allow that in the C++ code, WKT and PROJJSON, wheras it isn't allowed by the WKT spec. Actually we treat a BoundCRS as a CRS, whereas BoundCRS is only defined in WKT and its status is not clearly the one of a CRS but some object in-between a CRS and a transformation.

**Comment by kbevers** [comment]
> wheras it isn't allowed by the WKT spec

Does that mean we produce incorrect WKT? 

I'm not sure I've got a strong opinion on this matter. Ideally PROJJSON is a just a JSON representation of WKT but if WKT is insufficiently specced it makes sense to do something smarter with PROJJSON.

**Comment by rouault** [comment]
> we produce incorrect WKT?

yes, or "extended" in commercial terms :-)

**Comment by hernando** [comment]
As I understand, this change won't introduce anything invalid in a WKT2, it just extends PROJJSON with information that is known to the BoundCRS C++ class but can't be expressed in WKT2. The lack of this information renders the WKT2 ambiguous in the presence of a derived CRS as the base.
I would prefer to see a solution in the WKT standard, but despite I've raised the question in the OGC's coordtrans mailing list, the discussion didn't make any progress for almost 2 weeks.

**Comment by kbevers** [comment]
> yes, or "extended" in commercial terms :-)

Well, we are know to be quite commercial around here :-)

> I would prefer to see a solution in the WKT standard, but despite I've raised the question in the OGC's coordtrans mailing list, the discussion didn't make any progress for almost 2 weeks.

Adding to the standard is going to be a slow process. PROJJSON can possibly be used as a sort of beta test for new concepts that are candidates to be included in WKT. I think that's a good enough reason to merge this PR.

**Pull request merged**
