### PR TITLE
Add detection of MSVC 14.0 and 14.1+ to CMake configuration

### PR DESCRIPTION
**Pull request by mloskot**

### CODE REVIEW

**Comment by mloskot** [comment]
The failing build for this PR (https://travis-ci.org/OSGeo/proj.4/builds/280615212) is a mystery to me, at OSX it throws
```
$ cd OSGeo/proj.4
$ git fetch origin +refs/pull/580/merge:
fatal: Couldn't find remote ref refs/pull/580/merge
```

I assume it's not the PRs fault.

**Comment by kbevers** [comment]
Probably a Travis hickup. I've restarted the build to see if Travis behaves now.

**Comment by proj4docs** [comment]
I merged before Travis was done

**Comment by mloskot** [comment]
Its green now (https://travis-ci.org/OSGeo/proj.4/builds/280618787). Thanks @kbevers

**Pull request merged**
