### PR TITLE
Database: update to EPSG 9.9

### PR DESCRIPTION
**Pull request by rouault**
Note to Australian users (CC @nyalldawson ). There's a new geoid grid that should perhaps be included in PROJ-data (AGQG_20191107.gsb)
See
```
INSERT INTO "grid_transformation" VALUES('EPSG','9461','GDA2020 to AVWS height (1)','AGQG is used to realise AVWS. Uncertainties (4-8 cm across mainland Australia) given in accompanying file AGQG_uncertainty_20191107.gsb. For reversible alternative to this transformation see GDA2020 to GDA2020 + AVWS height (1) (code 9465).','Geodesy, hydrography, transfer of accurate heights over distances greater than 10km.','EPSG','1048','Geographic3D to GravityRelatedHeight (AUSGeoid v2)','EPSG','7843','EPSG','9458','EPSG','4177',0.1,'EPSG','8666','Geoid (height correction) model file','AGQG_20191107.gsb',NULL,NULL,NULL,NULL,NULL,NULL,'GA-Aus AGQG 20191107',0);
INSERT INTO "grid_transformation" VALUES('EPSG','9465','GDA2020 to GDA2020 + AVWS height (1)','Reversible alternative to GDA2020 to AVWS height (1) (code 9461). AGQG is used to realise AVWS. Uncertainties (4-8 cm across mainland Australia) given in accompanying file AGQG_uncertainty_20191107.gsb.','Derivation of gravity-related heights from GNSS observations.','EPSG','1083','Geog3D to Geog2D+Vertical (AUSGeoid v2)','EPSG','7843','EPSG','9462','EPSG','4177',0.1,'EPSG','8666','Geoid (height correction) model file','AGQG_20191107.gsb',NULL,NULL,NULL,NULL,'EPSG','7844','GA-Aus AGQG 20191107',0);
```

### CODE REVIEW

**Comment by jmckenna** [comment]
thanks @rouault

**Comment by nyalldawson** [comment]
Thanks for the heads-up @rouault ! I'll need to do some research into this one...

**Comment by jmckenna** [comment]
There has also been a subsequent 9.9.1 release, but it seems to be for one SQL insert error (I suppose we would have hit it when building the 9.9 PROJ db).

**Comment by rouault** [comment]
Just tried 9.9.1. There's no impact on PROJ. The change between 9.9 and 9.9.1 is on a field that isn't imported by PROJ.

**Pull request merged**
