### PR TITLE
Update horner.rst

### PR DESCRIPTION
**Pull request by Jochem-L**

### CODE REVIEW

**Comment by busstoptaktik** [comment]
@Jochem-L Thanks for following up on this. I cannot find time to review this PR within a reasonable time frame, but I think we should ask for comments from @georgeouzou, since he is the latest person to touch the Horner docs in any substantial way, in connection with his introduction of invertible polynomiums in #3133 and #3217 last year.

Unfortunately, I cannot add @georgeouzou as suggested reviewer - perhaps because one needs commit rights in order to review? But that would not prevent him from chiming in here in the comments

**Comment by georgeouzou** [comment]
Hi there! After checking the changes i have the following comments:
- The tables are nice to have but they contain _x_ and _y_ whereas the equations above use _U_ and _V_ instead. We could use either but we should be consistent.
- The indexing on the u and v parameters was (row, column). Now it seems switched to (column, row) which is in contrast to the added parameter tables.

**Comment by busstoptaktik** [comment]
@georgeouzou you may not be following the PROJ mailing list anymore, so for your information, the reasoning behind some of the material @Jochem-L provides has been elaborated somewhat on in a thread over at https://lists.osgeo.org/pipermail/proj/2023-November/011166.html

**Comment by Jochem-L** [comment]
@georgeouzou, Thanks for your great comments.
* I will change the x and y in de parameter tables to U and V, that seems the easiest way to keep it consistent.
* The problem with the indexing is the confusing convention in math to order coordinates differently than matrix indices.
  - In formula (1), the indexing is UV;
  - In the formula after (3), the indexing was VU. I suggested to change it to UV.
  - In the parameter description, the indexing was VU for U, and UV for V (and starting with 1 instead of 0). I suggested to make it to UV for both (and starting with 0).
  - For the parameter tables, I suggested the indexing UV with increasing U (x) horizontally and increasing V (y) vertically, which makes sense for coordinates, but indeed implies the col,row which is odd. I suggest to solve it by keeping the indexing UV everywhere and transposing the parameter tables to make them row,col.

```
The order of coefficients u_{i,j} is (example for degree 3):

+----+------+------+------+------+
|    | V⁰   | V¹   | V²   | V³   |
+----+------+------+------+------+
| U⁰ | 1st  | 5th  | 8th  | 10th |
+----+------+------+------+------+
| U¹ | 2nd  | 6th  | 9th  | –    |
+----+------+------+------+------+
| U² | 3rd  | 7th  | –    | –    |
+----+------+------+------+------+
| U³ | 4th  | –    | –    | –    |
+----+------+------+------+------+

The order of coefficients v_{i,j} is (example for degree 3):

+----+------+------+------+------+
|    | V⁰   | V¹   | V²   | V³   |
+----+------+------+------+------+
| U⁰ | 1st  | 2nd  | 3rd  | 4th  |
+----+------+------+------+------+
| U¹ | 5th  | 6th  | 7th  | –    |
+----+------+------+------+------+
| U² | 8th  | 9th  | –    | –    |
+----+------+------+------+------+
| U³ | 10th | –    | –    | –    |
+----+------+------+------+------+
```

Does that solve the inconsistencies you found?

**Comment by georgeouzou** [comment]
@Jochem-L all changes seem consistent and correct!

**Comment by busstoptaktik** [comment]
@Jochem-L so once you have updated the PR to reflect your comments above, I'm ready to merge the material

**Review by busstoptaktik — APPROVED** [review]
Looks good to me

**Comment by rouault** [comment]
The backport to `9.3` failed:
```
The process '/usr/bin/git' failed with exit code 128
```
<details>
<summary>stderr</summary>

```
error: commit a377a470ec807acb0c605c8ad587b33869aa2917 is a merge but no -m option was given.
fatal: cherry-pick failed

```
</details>

<details>
<summary>stdout</summary>

```
[backport-3964-to-9.3 027dbcc0] Update horner.rst
 Author: Jochem-L <55313523+Jochem-L@users.noreply.github.com>
 Date: Fri Nov 24 12:15:51 2023 +0100
 1 file changed, 34 insertions(+), 6 deletions(-)

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-9.3 9.3
# Navigate to the new working tree
cd .worktrees/backport-9.3
# Create a new branch
git switch --create backport-3964-to-9.3
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 0025bf0a0ca21ba7fa6e8daa740438f63d6ca1f9,a377a470ec807acb0c605c8ad587b33869aa2917,91b4bf7d725f0f94f8f580e2383b12a38885e486
# Push it to GitHub
git push --set-upstream origin backport-3964-to-9.3
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-9.3
```
Then, create a pull request where the `base` branch is `9.3` and the `compare`/`head` branch is `backport-3964-to-9.3`.

**Comment by mwtoews** [comment]
manually cherry-picked to `9.3` with 931c44ad484ca78cb1225f79b5ca1ea0d5444761

**Pull request merged**
