### PR TITLE
CMake: bump PROJ version to 5.1.0

### PR DESCRIPTION
**Pull request by mloskot**
Align version with the one defined in configure.ac.

https://github.com/OSGeo/proj.4/blob/3e8a1984e9ee662e74254704275c8e30791a5af0/configure.ac#L4-L5

## Tasklist

- [x] Update `PROJ_VERSION`
- [x] Update `PROJ_API_VERSION`
- [x] Update `PROJ_BUILD_VERSION`

How should I update the last two?

### CODE REVIEW

**Comment by mloskot** [comment]
OK. Yes, the master should be at least a step ahead from the release.

Still, I have no idea how to bump the API and the BUILD versions.

**Comment by kbevers** [comment]
Okay, just keep it at 5.1.0 here then. I'll take care of bumping all the various numbers once this is merged.

**Comment by mloskot** [comment]
So, are you happy to merge this as is?

**Comment by kbevers** [comment]
Yes. `PROJ_API_VERSION` and `PROJ_BUILD_VERSION` are correct. I simply must have missed updating the actual version number to 5.1.0 when i prepared the release :/

**Comment by mloskot** [comment]
You can merge or I do self-merge? Not sure what's the PRs policy :-)

**Comment by kbevers** [comment]
There's no policy :-) Maybe we should have one... I don't mind you merging things when you are confident that things are okay.

**Pull request merged**
