### PR TITLE
Update proj.1

### PR DESCRIPTION
**Pull request by jidanni**
Got rid of weird formatting, and flipped words around too.

 - [ ] Closes #xxxx
 - [ ] Tests added
 - [ ] Added clear title that can be used to generate release notes
 - [ ] Fully documented, including updating `docs/source/*.rst` for new API

### CODE REVIEW

**Comment by rouault** [comment]
This file is automatically generated from docs/source/apps/proj.rst . Only the later should be modified

**Comment by jidanni** [comment]
I thought I was smart by editing this, instead of raw nroff output, but as you say I wasn't smart enough.

Perhaps warnings could be placed in comments at the top of these files so others don't make the same mistake.

They could say be sure you're editing a .rst file instead of a .1 etc.file.

**Comment by rouault** [comment]
the first line is ".\" Man page generated from reStructuredText." . "generated" implies "do not modify it directly". I'm not sure we have much control on this first line. It is written by Sphinx.

**Comment by jidanni** [comment]
Seems like my eyeballs missed that obvious warning sign!

**Comment by jidanni** [comment]
All I know is in https://github.com/OSGeo/PROJ/edit/master/docs/source/apps/cs2cs.rst directly using that ..versionadded in the middle of the item makes ugly output... But for now I don't have the entire testbed installed.

```
.. option:: -d <n>

    .. versionadded:: 5.2.0

    Specify the number of decimals in the output.
```

So I'll drop the issue.

**Pull request closed without merging**
