### PR TITLE
Take into account new EPSG methods 'Cartesian Grid Offsets by TIN Interpolation (JSON)' and 'Vertical Offset by TIN Interpolation (JSON)'

### PR DESCRIPTION
**Pull request by rouault**
and remove custom transformations for Finland TIN base transformations that were previously under the PROJ authority

### CODE REVIEW

**Comment by rouault** [comment]
@phakli Now that EPSG:10703 is registered, would it make sense for you to also register in EPSG a concatenated operation for "KKJ to EUREF-FIN" using it that would chain EPSG:18193 ("Finland Uniform Coordinate System"), EPSG:10703 and EPSG:16065 ("TM35FIN" in inverse direction). That would enable us to remove the custom PROJ:KKJ_TO_EUREF_FIN that does exactly that.

**Comment by phakli** [comment]
Thanks @rouault. I sent a request to IOGP regarding the concatenated operation.

**Comment by rouault** [comment]
@jjimenezshaw you can now rebase on top of latest master

**Comment by phakli** [comment]
@rouault, the concatenated operation KKJ to EUREF-FIN (3) has now been registered: EPSG:10778 (https://epsg.org/concatenated-operation_10778/KKJ-to-EUREF-FIN-3.html)

**Comment by rouault** [comment]
> @rouault, the concatenated operation KKJ to EUREF-FIN (3) has now been registered: EPSG:10778 (https://epsg.org/concatenated-operation_10778/KKJ-to-EUREF-FIN-3.html)

yes, works well with https://github.com/OSGeo/PROJ/pull/4387 applied:
```
$ PROJ_DATA=data bin/projinfo -k operation EPSG:10778
PROJ string:
+proj=pipeline
  +step +proj=axisswap +order=2,1
  +step +proj=unitconvert +xy_in=deg +xy_out=rad
  +step +proj=tmerc +lat_0=0 +lon_0=27 +k=1 +x_0=3500000 +y_0=0 +ellps=intl
  +step +proj=tinshift +file=fi_nls_ykj_etrs35fin.json
  +step +inv +proj=utm +zone=35 +ellps=GRS80
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1
```

**Pull request merged**
