### PR TITLE
Doc: use 'version_selector' instead of 'display_version' which is deprecated by sphinx-rtd-theme 3.0.0

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by rouault** [comment]
hum for some reason the version selector in https://osgeo-proj--4270.org.readthedocs.build/en/4270/ doesn't appear where it does for pull requests still using RtD v2: https://osgeo-proj--4265.org.readthedocs.build/en/4265/

**Comment by rouault** [comment]
I'm also having the same issue with GDAL docs. Cf https://github.com/OSGeo/gdal/pull/10954

**Comment by rouault** [comment]
> hum for some reason the version selector in https://osgeo-proj--4270.org.readthedocs.build/en/4270/ doesn't appear

hum that's more subtle.
It does not appear in the index page: https://osgeo-proj--4270.org.readthedocs.build/en/4270/
but it appears in any sub-page: https://osgeo-proj--4270.org.readthedocs.build/en/4270/about.html

**Comment by jjimenezshaw** [comment]
Does it appear as a floating window as in gdal? Not in the menu bar?
I thought we were going to change gdal to be like proj, not the other way around

**Comment by rouault** [comment]
> Does it appear as a floating window as in gdal? Not in the menu bar?
> I thought we were going to change gdal to be like proj, not the other way around

yes, this PR doesn't intend to bring GDAL custom theme to PROJ. I just try to make the minimum changes due to the https://about.readthedocs.com/blog/2024/07/addons-by-default/ changes and the related bump of sphinx-rtd-theme to 3.0.0

**Comment by rouault** [comment]
hum, actually the issue about the selector missing is just an issue with browser caching... So, I believe this PR is fine to go.

**Comment by rouault** [comment]
The backport to `9.5` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 58a7a148... Doc: use 'version_selector' instead of 'display_version' which is deprecated by sphinx-rtd-theme 3.0.0
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
CONFLICT (modify/delete): .github/workflows/doc_checks.yml deleted in HEAD and modified in 58a7a148 (Doc: use 'version_selector' instead of 'display_version' which is deprecated by sphinx-rtd-theme 3.0.0).  Version 58a7a148 (Doc: use 'version_selector' instead of 'display_version' which is deprecated by sphinx-rtd-theme 3.0.0) of .github/workflows/doc_checks.yml left in tree.
Auto-merging docs/source/conf.py

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-9.5 9.5
# Navigate to the new working tree
cd .worktrees/backport-9.5
# Create a new branch
git switch --create backport-4270-to-9.5
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 58a7a1488728a67e06bbc5b6e6d8af834268cf19,eb25d7154c9d35124ff0d2d24d7818a1a5620e32
# Push it to GitHub
git push --set-upstream origin backport-4270-to-9.5
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-9.5
```
Then, create a pull request where the `base` branch is `9.5` and the `compare`/`head` branch is `backport-4270-to-9.5`.

**Comment by rouault** [comment]
9.5 backport in https://github.com/OSGeo/PROJ/pull/4272

**Pull request merged**
