### PR TITLE
Set version number and improve documentation

### PR DESCRIPTION
**Pull request by desruisseaux**
Regarding the discussion on https://github.com/OSGeo/proj.4/issues/903#issuecomment-387681803, this merge request:

* Fixes the version number to 3.0 for consistency with the `README.md` text, which said "This is the third release of JNI wrappers". Another rational is that the same JAR version is compatible with a range of PROJ releases. Documentation in the `README.md` file has been made more explicit.
* Does not change the build configuration regarding the `org_proj4_PJ.h` file location (my attempts to change the makefile process were unsuccessful). Instead, after `javac` generated the `org_proj4_PJ.h` file, move that file to the C `src/` directory.

### CODE REVIEW

**Comment by kbevers** [comment]
Is it the Autotools makefiles you have trouble with or is it something Java-related? I am not sure I understand where `org_proj4_PJ.h` is kept now. In `src/`?

**Comment by desruisseaux** [comment]
It was with the Autotools makefiles; after updating the path of every `org_proj4_PJ.h` occurrences found in the code base, then deleting `src/.deps` and running `autoreconf -f -i` (as a paranoiac safety), running configure, every thing succeed up to that point. But then running `make` produces an error message saying that there is no rule telling how to create `org_proj4_PJ.h` (I do not have anymore the exact error message at hand).

The exact location of `org_proj4_PJ.h` may not be a major issue. It is generated automatically by `javac`, but the result is identical to the file committed on git. The above merge request moves the generated file to the current location of `org_proj4_PJ.h`, but given that those files are identical (at least for now) this is equivalent to just deleting the file generated by `javac`.

**Comment by desruisseaux** [comment]
Integration builds failed apparently for networking reasons:

```
--2018-05-12 17:24:58--  http://download.osgeo.org/proj/proj-datumgrid-1.5.zip
Connecting to download.osgeo.org (download.osgeo.org)|140.211.15.132|:80...
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
```

```
--2018-05-12 16:51:39--  http://download.osgeo.org/proj/proj-datumgrid-1.7.zip
Connecting to download.osgeo.org (download.osgeo.org)|140.211.15.132|:80...
failed: Connection refused.
```

```
curl -O http://download.osgeo.org/proj/proj-datumgrid-1.7.zip
0curl: (7) Failed to connect to download.osgeo.org port 80: Timed out
```

**Comment by kbevers** [comment]
I've restarted the Travis builds. Unfortunately I haven't got access to restarting the Appveyor builds.

**Comment by kbevers** [comment]
Thanks. Are you happy with this as it is now, @desruisseaux ?

**Comment by desruisseaux** [comment]
Yes, I'm done for making the current binding up-to-date with latest Java versions. The next step would be to use the new PROJ API, but I have not yet investigated the changes compared to Proj.4 API.

**Comment by kbevers** [comment]
> Yes, I'm done for making the current binding up-to-date with latest Java versions. The next step would be to use the new PROJ API, but I have not yet investigated the changes compared to Proj.4 API.

The changes are substantial so I would expect it to take some time to implement.

Are the current Java API depending on `projects.h` or is it purely using `proj_api.h`?

**Comment by desruisseaux** [comment]
It uses `projects.h`, mostly because (at the time `jniproj.c` was created) it was the most convenient way I found to read information like `PJ.a_origin`, `PJ.es_orig`, `PJ.from_greenwich`, _etc._ Those read accesses are for allowing users to populate OGC-like `CD_Datum` or `CS_CoordinateSystem` objects if they need.

**Comment by kbevers** [comment]
Okay. `projects.h` will be removed from the public API with PROJ version 6. So it would be nice to not have that dependency when 6.0 is released in February next year.

**Pull request merged**
