### PR TITLE
Extend proj_strtod test cases and improve strtod-replication

### LINKED ISSUE #623: gie parses input incorrectly in some cases
As demonstrated below. I did a quick debug session and determined that the expect coordinates are not properly read. If I change the "0" to "0." or "0.0" the test passes. Similar to the recent issue with cct, although the fix to that should apply here as well.

```
$ cat dev/proj4/test/fail.gie
BEGIN

--------------------------------------------------
OPERATION +proj=pipeline +step +init=epsg:4283 +inv +step +init=epsg:3577
TOLERANCE 0.05m
--------------------------------------------------
ACCEPT    132 -27
EXPECT    0 -2926820.89

END                                                                                                                                                            
$ gie dev/proj4/test/fail.gie
-------------------------------------------------------------------------------
Reading file 'dev/proj4/test/fail.gie'
-------------------------------------------------------------------------------
+proj=pipeline +step +init=epsg:4283 +inv +step +init=epsg:3577
-------------------------------------------------------------------------------
     FAILURE in fail.gie(8):
     expected: 0 -2926820.89
     got:      0.000000000   -2926820.886839157   0.000000000   0.000000000
     deviation:  9999.999 mm,  expected:  50.000 mm
-------------------------------------------------------------------------------
total:  0 tests succeeded,   1 tests FAILED!
-------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by busstoptaktik**
Resolves #623

### CODE REVIEW

**Comment by kbevers** [comment]
Unfortunately this introduced a new error:

```
$ cat test/fail.gie
BEGIN
--------------------------------------------------
OPERATION +proj=pipeline +step +init=epsg:4283 +inv +step +init=epsg:3577
--------------------------------------------------
TOLERANCE 0.006 m
ACCEPT    132 0
ROUNDTRIP 1000

END
$ gie test/fail.gie
-------------------------------------------------------------------------------
Reading file 'test/fail.gie'
-------------------------------------------------------------------------------
+proj=pipeline +step +init=epsg:4283 +inv +step +init=epsg:3577
-------------------------------------------------------------------------------
     FAILURE in fail.gie(7):
     roundtrip deivation: 0.000 mm, expected: 0.000 mm
-------------------------------------------------------------------------------
total:  0 tests succeeded,   1 tests FAILED!
-------------------------------------------------------------------------------
```

Tolerance does not seem to be read correctly when doing roundtrip tests. Also, "deviation" is misspelled :)

**Comment by busstoptaktik** [comment]
I do not think this bug is in proj_strtod: I have just added the two tests "0.006" and "0.006 " to my local copy, and they come out identical to the libc strtod.

Will look into whether it's a `gie.c` thing.

**Comment by busstoptaktik** [comment]
It's a consequence of trying harder to mimic the system strtod, by again returning 0 in case of invalid input.
Updating in a moment

**Comment by busstoptaktik** [comment]
Done.

**Pull request merged**
