### PR TITLE
CMake: set RUN_NETWORK_DEPENDENT_TESTS to ON by default only if network seems available (fixes #3060)

### LINKED ISSUE #3060: nkg test fails in environments without network and proj-data installed
The Debian package build for 9.0.0-rc1 failed due to test failures.

#### Example of problem
```
      Start 19: nkg
19: Test command: /build/proj-9.0.0~rc1/obj-x86_64-linux-gnu/bin/gie "/build/proj-9.0.0~rc1/test/gie/nkg.gie"
19: Environment variables: 
19:  PROJ_USER_WRITABLE_DIRECTORY=/build/proj-9.0.0~rc1/obj-x86_64-linux-gnu/tmp_user_writable_dir
19:  PROJ_NETWORK=ON
19:  PROJ_LIB=/build/proj-9.0.0~rc1/obj-x86_64-linux-gnu/data/for_tests
19: Test timeout computed to be: 1500
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: proj=deformation (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf17vel.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf17vel.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf17vel.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: proj=deformation (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: proj=deformation (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf17vel.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: proj=deformation (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf17vel.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: proj=deformation (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf17vel.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: proj=deformation (File not found or invalid)
19: -------------------------------------------------------------------------------
19: Reading file '/build/proj-9.0.0~rc1/test/gie/nkg.gie'
19:      -----
19:      FAILURE in nkg.gie(10):
19:      expected: 3541657.9311 948983.7980 5201383.2227 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(23):
19:      expected: 3541657.9362 948983.7825 5201383.2292 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(30):
19:      expected: 3541657.3829 948984.2188 5201383.5296 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(40):
19:      expected: 3513638.5607 778956.1875 5248216.2477 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(44):
19:      expected: 3582105.2916 532589.7310 5232754.8057 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(51):
19:      expected: 3513638.5071 778956.1528 5248216.2870 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(55):
19:      expected: 3582105.2401 532589.6950 5232754.8507 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(62):
19:      expected: 3513638.5607 778956.1875 5248216.2477 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(66):
19:      expected: 3582105.2916 532589.7310 5232754.8057 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(78):
19:      expected: 3541657.9395 948983.8006 5201383.2242 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(85):
19:      expected: 3541657.3862 948984.2370 5201383.5246 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(95):
19:      expected: 2922028.2730 1516183.5457 5444680.4094 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(107):
19:      expected: 3541657.9522 948983.7911 5201383.2230 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(114):
19:      expected: 3541657.3989 948984.2274 5201383.5235 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(124):
19:      expected: 2994012.5170 1112559.5902 5502271.7683 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(137):
19:      expected: 3541657.9806 948983.8606 5201383.3118 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(144):
19:      expected: 3541657.4273 948984.2970 5201383.6122 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(153):
19:      expected: 3226814.9950 1449250.1841 5289639.3779 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(166):
19:      expected: 3541657.9358 948983.8042 5201383.2294 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(173):
19:      expected: 3541657.3826 948984.2405 5201383.5299 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000Cannot open https://cdn.proj.org/eur_nkg_nkgrf17vel.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: proj=deformation (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf17vel.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf03vel_realigned.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: proj=deformation (File not found or invalid)
19: Cannot open https://cdn.proj.org/eur_nkg_nkgrf17vel.tif: Could not resolve host: cdn.proj.org
19: deformation: could not find required grid(s).)
19: pipeline: Pipeline: Bad step definition: inv (File not found or invalid)
19:  mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(182):
19:      expected: 3343600.9945 1580417.5661 5179337.1637 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(195):
19:      expected: 3541657.9204 948983.8049 5201383.2054 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(202):
19:      expected: 3541657.3671 948984.2412 5201383.5058 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(211):
19:      expected: 3275753.9111 321110.8658 5445041.8822 2020.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(215):
19:      expected: 2391774.5535 615614.9100 5860965.8138 2020.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(219):
19:      expected: 2107889.5097 895603.2085 5933242.3152 2020.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(231):
19:      expected: 3541657.9223 948983.7912 5201383.2025 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(238):
19:      expected: 3541657.3690 948984.2275 5201383.5030 2020.5
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  1.000000 mm
19:      -----
19:      FAILURE in nkg.gie(247):
19:      expected: 2441775.4338 799268.0336 5818729.1635 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(251):
19:      expected: 2391774.5409 615614.8770 5860965.8078 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19:      -----
19:      FAILURE in nkg.gie(255):
19:      expected: 2248123.5028 865686.5301 5886425.5928 2015.0
19:      got:      inf   inf   inf   inf
19:      deviation:  999999999.999000 mm,  expected:  0.100000 mm
19: -------------------------------------------------------------------------------
19: total:  0 tests succeeded,  0 tests skipped, 31 tests FAILED!
19: -------------------------------------------------------------------------------
22/58 Test #19: nkg ..............................***Failed    0.26 sec
```
#### Problem description

The PROJ < 9 builds only required a few grids and none of proj-data grids.

#### Expected Output

Test pass.

#### Environment Information
 - PROJ version (`proj`): 9.0.0-rc1
 - Operation System Information: Debian unstable

#### Installation method
 - Debian package

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by rouault** [comment]
The Windows part doesn't seem to work as I see in the Windows workers
```
CMake Warning at test/CMakeLists.txt:22 (message):
  No network connection detection.  Skipping nkg.gie test
```

**Comment by rouault** [comment]
modified commit now works with Windows workers

**Comment by QuLogic** [comment]
Can this check be done only if `RUN_NETWORK_DEPENDENT_TESTS` is not explicitly specified already (instead of always running in order to determine the default)?

**Comment by rouault** [comment]
> Can this check be done only if `RUN_NETWORK_DEPENDENT_TESTS` is not explicitly specified already (instead of always running in order to determine the default)?

good idea. done

**Pull request merged**
