### PR TITLE
Add support for MISR SOM projection

### PR DESCRIPTION
**Pull request by mbull2016**

### CODE REVIEW

**Comment by mbull2016** [comment]
This new branch now has only the changes needed for MISR SOM projection.  

I think the previous request (#358) got confusing because I inadvertantly merged upstream changes into my push request.

**Comment by hobu** [comment]
This is looking pretty good.

Can you update the source code with a few comments or links to reflect where it came from?

**Comment by mbull2016** [comment]
The code is essentially a copy of PJ_lsat.c with some minor changes.  I've added a comment describing the differences.

**Comment by hobu** [comment]
Sorry to keep nagging, but is there any chance to add a test or two for expected output?

**Comment by mbull2016** [comment]
No problem.  Test cases for forward and inverse misrsom are added.

**Comment by hobu** [comment]
Excellent! Thanks so much for the contribution!

**Pull request merged**
